### ISSUE TITLE
File download from FUSE is much slower compared to CLI

### ISSUE THREAD

**Issue by vi** [whoozle/android-file-transfer-linux#102]
Moving discussion from #89 

File reading speed through FUSE wrapper is only 3 MB/sec (with or without -o debug). With aft-mtp-cli 'get Music/q.tta' I has 14 MB/sec.

> try -o big_writes

Is `big_writes` expected to affect reading as well?

>  actually fuse and cli/gui use different MTP features for reading/writing.

> fuse uses partial objects read/write, which are handled by mtp server from userspace.
CLI/GUI interfaces use SendObject/GetObject which is handled by linux gadget driver from kernel space. No page extra copying added in this case + thin layer of usb waiting via work queues.

Maybe the buffer size for "partial" thing is too small? Maybe small enough files can be read as a whole and cached?

**Comment by whoozle** [comment]
buffer for partial request allocated on the fuse/kernel side.

**Comment by vi** [comment]
One FUSE syscall can correspond to less than one MTP "transaction"...

Also need to experiment with `-o direct_io`

**Comment by whoozle** [comment]
so what? partial api is slower than send/getobject by design. 
you could try, but i think it will be slower, because kernel caching and readahead will not work in this mode.

**Comment by whoozle** [comment]
you could try set up different values in Init(), like maxreadahead and capabilities and figure out what will work best for you. 
Preferably using -ll version, because I believe this will be default in future.

**Comment by vi** [comment]
Maybe it is slower by design, but I expect the tradeoff to be "N per cent slower" instead of "N times slower". With buffer size -> file size, I expect it to be around the speed of non-partial mode.

**Comment by vi** [comment]
`-o direct_io` + large buffer size + edited FUSE_MAX_PAGES_PER_REQ in kernel = 4.5 MB/s. Still not even near 14 MB/s.

Actually I excepted either USB (prefereably with USB 3.0 speed) link or device's flash to be bottleneck for single file download. `adb pull` also runs at `4270 KB/s`...

**Comment by whoozle** [comment]
with new fuse code I got 10-11Mb/s (nexus 5) without any tweaking and/or direct_io option. please pull.

Also, note that -ll wrapper does not build anymore, remove it from build directory or remove whole build/ directory!

**Comment by whoozle** [comment]
so, can we close it now?
