### ISSUE TITLE
Feature: disable automatic start when device plugged in

### ISSUE THREAD

**Issue by GrayedFox** [whoozle/android-file-transfer-linux#105]
There are posts all over the net about how to do this... but really, it is a (relatively) simple feature to implement, I would guess?

A nice little boolean / checkbox present on the UI or perhaps adding a preferences menu would do it :+1:

**Comment by whoozle** [comment]
sorry, but I don't start anything or even listen for usb plug events!

**Comment by GrayedFox** [comment]
I think I am confusing this git with android file transfer for mac? My apologies!

**Comment by whoozle** [comment]
BTW I ported this software to Mac and I hope next release will come out for Mac OS X too :)

It will not start I promise (also will not freeze your computer and turn off external usb devices like mices and keyboards) :D
