### ISSUE TITLE
Feature request: renaming files using FUSE wrapper

### ISSUE THREAD

**Issue by vi** [whoozle/android-file-transfer-linux#107]
Now it says `Function not implemented`.

Reverted to `adb shell` for organizing my files.

**Comment by whoozle** [comment]
What exactly was not implemented?

**Comment by whoozle** [comment]
Oh, sorry, I got it. Will add it soon.

**Comment by whoozle** [comment]
The problem is mtp MoveObject does not work in any implementation I saw, now I return EXDEV, so please check. it should work (kinda slow, because user-space program which got EXDEV must recreate file and copy old into new one)

**Comment by whoozle** [comment]
does it work now?

**Comment by vi** [comment]
I'll check later. 

I was trying to organize music a bit, but got stopped by two errors: missing renaming and the hangs while playing (reproduced about 4 times). I'll file about the second issue later.

**Comment by whoozle** [comment]
any luck with that? :)

**Comment by vi** [comment]
Haven't checked yet... Maybe will check soonish.

**Comment by vi** [comment]
Renaming seems to work, but ugly (as if it were two separate devices, copy+delete). I also expect it to fail if there is little free space.

Maybe use the fallback behaviour only for small files? If normal renaming is not supported and it is expected to take more time to rename though the AFT compared to renaming in a file manager on the device itself (including switching from computer to device and using virtual keyboard), then return `ENOTSUP`...

**Comment by whoozle** [comment]
Unfortunatelly, no implementation supports MoveObject command. Nothing could be done here, you can neither rename nor set new parent. I studied sources and experimented with real devices with no success. 

No space error is thrown by underlying API (mtp server), I have no reliable way to check free space. No filesystem driver does it, though, your file manager should create files with "truncate" operation, not open + sequence of writes. Feel free to file bug there (implement mtp Move/CopyObject command):
https://code.google.com/p/android/issues/list

**Comment by vi** [comment]
> Unfortunatelly, no implementation supports MoveObject command.

But AFT should always try it first, reverting to fall back behaviour when got "no implemented" command.

Otherwise MTP server developers would thing "no clients use MoveObject anyway" and omit MoveObject.

Also what do you think about file size limit for fallback rename? It's not easy to stop rename once it has started, leading to "I should have just renamed it on device" feeling.

**Comment by whoozle** [comment]
No need to try, it's just not on the 'supported commands' list. Filing an issue will be more effictive. 
What kind of fallback are you talking about? I don't understand. I can implement truncate/open/write/close sequence, but it's *exactly* what EXDEV will do.
