### ISSUE TITLE
OSX make- error: value of type 'mtp::usb::RequestType' is not implicitly convertible to 'u8' (aka 'unsigned char')

### ISSUE THREAD

**Issue by sleepingscorpion** [whoozle/android-file-transfer-linux#109]
HI,

Getting the following after initiating make on OSX 10.11.1, please let me know what other info you need, environment vars etc.

Cloned from git, installed QT4 via brew, did cmake .. ---> make

Thanks

$ cmake ..
-- The C compiler identification is AppleClang 7.0.2.7000181
-- The CXX compiler identification is AppleClang 7.0.2.7000181
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- building for Darwin
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Looking for include file magic.h
-- Looking for include file magic.h - not found
-- Looking for magic_open in magic
-- Looking for magic_open in magic - not found
-- Found Readline: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include  
-- Using Qt4
-- Configuring done
-- Generating done
-- Build files have been written to: /Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/build
IAs-MBP-2:build ia$ make
Scanning dependencies of target mtp-ng-static
[  1%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/log.cpp.o
[  3%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/ByteArray.cpp.o
[  5%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/ptp/Device.cpp.o
In file included from /Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/mtp/ptp/Device.cpp:29:
/Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/./mtp/usb/Request.h:62:16: error: value of type
      'mtp::usb::RequestType' is not implicitly convertible to 'u8' (aka 'unsigned char')
                        DeviceOut       = RequestType::HostToDevice | RequestType::Standard | RequestType::Device,
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/./mtp/usb/Request.h:63:15: error: value of type
      'mtp::usb::RequestType' is not implicitly convertible to 'u8' (aka 'unsigned char')
                        DeviceIn        = RequestType::DeviceToHost | RequestType::Standard | RequestType::Device
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/./mtp/usb/Request.h:98:19: error: value of type
      'mtp::usb::RequestType' is not implicitly convertible to 'u8' (aka 'unsigned char')
                        InterfaceOut    = RequestType::HostToDevice | RequestType::Standard | RequestType::Interface,
                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/./mtp/usb/Request.h:99:19: error: value of type
      'mtp::usb::RequestType' is not implicitly convertible to 'u8' (aka 'unsigned char')
                        InterfaceIn             = RequestType::DeviceToHost | RequestType::Standard | RequestType::Interface
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/./mtp/usb/Request.h:129:18: error: value of type
      'mtp::usb::RequestType' is not implicitly convertible to 'u8' (aka 'unsigned char')
                        EnpointOut              = RequestType::HostToDevice | RequestType::Standard | RequestType::Endpoint,
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/./mtp/usb/Request.h:130:17: error: value of type
      'mtp::usb::RequestType' is not implicitly convertible to 'u8' (aka 'unsigned char')
                        EnpointIn               = RequestType::DeviceToHost | RequestType::Standard | RequestType::Endpoint
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
6 errors generated.
make[2]: *** [CMakeFiles/mtp-ng-static.dir/mtp/ptp/Device.cpp.o] Error 1
make[1]: *** [CMakeFiles/mtp-ng-static.dir/all] Error 2
make: *** [all] Error 2

**Comment by whoozle** [comment]
Just fixed clang compilation, commit 1a6e05af1eae0377f06582f2996e57fdce2f44f5

**Comment by sleepingscorpion** [comment]
Thanks. Slightly different issues now:

IAs-MBP-2:android-file-transfer-linux ia$ git pull
remote: Counting objects: 6, done.
remote: Total 6 (delta 5), reused 5 (delta 5), pack-reused 1
Unpacking objects: 100% (6/6), done.
From https://github.com/whoozle/android-file-transfer-linux
   207f5f0..1a6e05a  master     -> origin/master
Updating 207f5f0..1a6e05a
Fast-forward
 mtp/usb/Request.cpp |  2 +-
 mtp/usb/Request.h   | 12 ++++++------
 2 files changed, 7 insertions(+), 7 deletions(-)
IAs-MBP-2:android-file-transfer-linux ia$ cd build/
IAs-MBP-2:build ia$ cmake ..
-- building for Darwin
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Using Qt4
-- Configuring done
-- Generating done
-- Build files have been written to: /Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/build
IAs-MBP-2:build ia$ make
Scanning dependencies of target mtp-ng-static
[  1%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/ptp/Device.cpp.o
[  3%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/ptp/ObjectFormat.cpp.o
[  5%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/ptp/PipePacketer.cpp.o
[  7%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/ptp/Response.cpp.o
/Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/mtp/ptp/Response.cpp:84:97: warning: format specifies type
      'unsigned short' but the argument has type 'unsigned int' [-Wformat]
                        snprintf(buf, sizeof(buf), "invalid response code %s (0x%04hx)", GetResponseName(r).c_str(), (unsigned)r);
                                                                                ~~~~~                                ^~~~~~~~~~~
                                                                                %04x
1 warning generated.
[  9%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/ptp/Session.cpp.o
[ 10%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/usb/BulkPipe.cpp.o
[ 12%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/usb/Request.cpp.o
[ 14%] Building CXX object CMakeFiles/mtp-ng-static.dir/mtp/backend/darwin/usb/Context.cpp.o
/Volumes/disk1s1/Users/ia/sgs4-firmware/android-file-transfer-linux/mtp/backend/darwin/usb/Context.cpp:74:6: error: use of
      undeclared identifier 'error'
                        { error(ex.what()); }
                          ^
1 error generated.
make[2]: *** [CMakeFiles/mtp-ng-static.dir/mtp/backend/darwin/usb/Context.cpp.o] Error 1
make[1]: *** [CMakeFiles/mtp-ng-static.dir/all] Error 2
make: *** [all] Error 2

**Comment by whoozle** [comment]
I cannot check on macosx now, sorry, but try again with revision 07ed594d9d7a78d7b736a15c2a712a1006b54139

**Comment by whoozle** [comment]
does it compile now?

**Comment by whoozle** [comment]
@gazay fixed compilation in https://github.com/whoozle/android-file-transfer-linux/pull/110

**Comment by sleepingscorpion** [comment]
sorry for late reply, compiles ok now. many thanks

**Comment by whoozle** [comment]
thanks for feedback! :)
