### ISSUE TITLE
invalid response code InvalidObjectHandle

### ISSUE THREAD

**Issue by vvviperrr** [whoozle/android-file-transfer-linux#118]
Хоть и сказано, что такое случается "иногда", по факту невозможно залить диру с кучей файлов. К примеру, у меня книги весят под 10 гиг, после копирования 10-20 штук все падает на 

> uploading file  "/home/viper/Desktop/Books/cs/focs.pdf"
> uploadFile  "focs.pdf"  as  "focs.pdf"
> sending  3918275  bytes
> uploading file  "/home/viper/Desktop/Books/cs/focs.pdf"  failed:  "SendObjectInfo: invalid response code InvalidObjectHandle (0x2009)"

т.е пользоваться вообще невозможно. классический AFT работает норм.

**Comment by whoozle** [comment]
хм, а если через aft-mtp-mount? баг ui наверное.

**Comment by whoozle** [comment]
Что значит классический AFT? У вас MacOSX?

**Comment by vvviperrr** [comment]
да, я говорю про маковский aft. просто ты на лоре рассказывал как он глючит)

**Comment by vvviperrr** [comment]
нет, тестил сейчас все на линуксе

**Comment by whoozle** [comment]
ну если он работает у вас, пользуйтесь им. :)
попробуйте залить через fuse пожалуйста. если там всё работает, то проблема в ui.

**Comment by vvviperrr** [comment]
>хм, а если через aft-mtp-mount
нет времени заниматься тестированием. просто проверил насколько оно "готово". баг описал.

**Comment by whoozle** [comment]
что ж, спасибо и на этом. :)
