### ISSUE TITLE
Удаление большого числа файлов

### ISSUE THREAD

**Issue by vvviperrr** [whoozle/android-file-transfer-linux#119]
При попытке сабжа прога падает на необработанном эксепшене. Логи уехали(

**Comment by whoozle** [comment]
что за телефон? попробуйте всё-таки эксепшон увидеть, без него нельзя ничего сделать. timeout?

**Comment by vvviperrr** [comment]
да влом опять заливать 10 гиг заново. нет, не таймаут. какой-то стандартный крестовый эксепшн.  телефон тут ни при чем (xperia tablet z3 compact, если интересно, 6 андроид). еще раз, маковский  aft работает как часы.

**Comment by whoozle** [comment]
если работает, повезло вам. :)

**Comment by whoozle** [comment]
будем считать починено в 6a5de2790fac25c469393731300d0b4f11fa66f9
