### ISSUE TITLE
Do we really need MTP?

### ISSUE THREAD

**Issue by vvviperrr** [whoozle/android-file-transfer-linux#120]
А ты не думал отказаться от MTP?

**Comment by whoozle** [comment]
лолшто? :) в каком смысле отказаться? со стороны телефона кто будет слушать?

**Comment by vvviperrr** [comment]
свой сервис.

**Comment by whoozle** [comment]
велосипеды-велосипедики. нет, слишком много работы, поддержки, непонятные перспективы, невозможность монетизации.

**Comment by d1vanov** [comment]
А между тем, есть проект KDE connect, в котором такая идея по сути и реализована:
https://community.kde.org/KDEConnect
https://github.com/albertvaka/kdeconnect-android/
https://github.com/albertvaka/kdeconnect-kde/
И кстати, "_KDE Connect implements a secure communication protocol over the network, and allows any developer to create plugins on top of it_".

**Comment by whoozle** [comment]
Крутой проект, да. Зачем вы тут это пишете? :)

**Comment by d1vanov** [comment]
Не для рекламы, отношения к этому проекту не имею, даже не пользуюсь сам) 
Пишу к тому, что можно, например, попытаться заиспользовать уже имеющуюся вещь для своих нужд, необязательно делать свой велосипед с нуля.

**Comment by whoozle** [comment]
А, да, я понял уже, поэтому удалил свой комментарий. Странный вопрос изначально, так можно в тракере хрома/ff создать баг — а вы не думали отказаться от html? :+1:

**Comment by d1vanov** [comment]
Хаха )
А кроме шуток, уже много болтовни о том, что HTML + JS + CSS - это ужасно, надо срочно заменить это все на что-то нормальное ))

Думаю, вопрос вызван тем, что с MTP действительно очень уж много проблем и как-то подспудно возникает желание от него совсем отгородиться. Опыт людей из KDE показывает, что это в принципе возможно, это был весь мой поинт )

**Comment by vvviperrr** [comment]
>Странный вопрос изначально
Не вижу ничего странного. твоя цель передавать файлы или запилить еще одну глючную реализацию mtp?

**Comment by whoozle** [comment]
Ой-ой, всё пропало, тушеночная невеста нас тут всех разоблачила! 

Пишите ещё, мнение хамоватых школьников с лора очень важно для нас.

**Comment by vvviperrr** [comment]
и в чем же мое хамство? я спросил про отказ от mtp без всякой задней мысли (сам копался в gmptfs). и что ты мне ответил?
>лолшто? 
и кто тут хам?)

по поводу глючности твоей реализации?
ну смотри. я клонировал репу, сборка упала на линковке, это раз. попытался удалить файло - прога упала, это два. попытался залить файло - засыпала ошибками, это три. учитывая что 2.4 версия вышла год назад сделал соответствующие выводы.

**Comment by whoozle** [comment]
Ну во-первых, тыкать незнакомым людям неприлично, а во-вторых, вы с таким апломбом здесь выступаете, будто я таки вам денег должен. Лицензию читали? Не нравится — не пользуйтесь, ой вей, никто никого не заставляет. За баги спасибо конечно земное, но без дополнительного исследования с вашей стороны они особой ценности не имеют. У меня, в общем, такая же нога и она не болит.

**Comment by vvviperrr** [comment]
>Ну во-первых, тыкать незнакомым людям неприлично

действительно, мое упущение. я то пытался говорить на равных, как с коллегой.
>а во-вторых, вы с таким апломбом здесь выступаете, будто я таки вам денег долж

Вам моказалось

>Лицензию читали? Не нравится — не пользуйтесь, ой вей, никто никого не заставляет

а Вы не обманывайте народ:
>Android File Transfer for Linux — свободная и стабильная реализация протокола MTP
>стабильная

>но без дополнительного исследования с вашей стороны они особой ценности не имеют

я бы с радостью прислал файл с логом, но его нет.
