### ISSUE TITLE
WP8 support regress

### ISSUE THREAD

**Issue by trufanov-nok** [whoozle/android-file-transfer-linux#122]
It has been a while since I update AFTL from github so I decided to check up-to-date version. Unfortunately I found out that my Lumia doesn't work with it.
Firstly I tried the binary I had and it worked.
Then I pulled current master branch, overwrite binary and tried it - it wasn't able to connect to device as "Device doesn't respond". The output is [here](http://pastebin.com/Um1TriwL).
Then I've uncommented HexDump() func in Device.cpp and tried again. The output is [here](http://pastebin.com/70jsX5wp). Once it was able to display the root folder of my device but GUI crashed just after I tried to open any folder in it.
My current system is Kubuntu 16.04. Device fw is the same.
I can try to bisect the commit that broke WP support if necessary.

**Comment by whoozle** [comment]
It would be perfect if you can bisect, yes. I made a lot of changes, adding support for Mac, parsing USB descriptors, etc

**Comment by trufanov-nok** [comment]
git bisect says the problem appeared at this point:
`[16023c5c31dea32e1bb0a90e0220a2476bc27663] removed default timeouts from pipe packeter`

**Comment by trufanov-nok** [comment]
After some tuning of timeout in [Reap() function](https://github.com/whoozle/android-file-transfer-linux/blob/master/mtp/backend/linux/usb/Device.cpp#L181) I found out that I need at least 5000 timeout instead of 3000 to connect to my Lumia.

**Comment by whoozle** [comment]
You could either file me pull request with greater timeout value, or I can do it myself. 

It seems that I have to do #46 in this release, as soon as possible. This could remove the need of timeout at all, so everyone could wait any amount of time with cancel possibility.

**Comment by trufanov-nok** [comment]
Please do it yourself as you want.

2016-05-04 17:35 GMT+03:00 Vladimir <notifications@github.com>:

> You could either file me pull request with greater timeout value, or I can
> do it myself.
>
> It seems that I have to do #46
> <https://github.com/whoozle/android-file-transfer-linux/issues/46> in
> this release, as soon as possible. This could remove the need of timeout at
> all, so everyone could wait any amount of time with cancel possibility.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/whoozle/android-file-transfer-linux/issues/122#issuecomment-216884633>
>



-- 
With best regards,
Alexander Trufanov

**Comment by whoozle** [comment]
Cleaned up a little in ffec4142c1f393960575d1a98a9d320ad2aae3e7 and 1d0c31e3c637f743c1c9a3d8d382fd9a04185671.

Can you pull & check please?

**Comment by trufanov-nok** [comment]
Thanks, this seems to fix the problem.
I'll probably make better testing later and turn back if something wrong.
Till that you may close the issue.

2016-05-04 19:13 GMT+03:00 Vladimir <notifications@github.com>:

> Cleaned up a little in ffec414
> <https://github.com/whoozle/android-file-transfer-linux/commit/ffec4142c1f393960575d1a98a9d320ad2aae3e7>
> and 1d0c31e
> <https://github.com/whoozle/android-file-transfer-linux/commit/1d0c31e3c637f743c1c9a3d8d382fd9a04185671>
> .
>
> Can you pull & check please?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/whoozle/android-file-transfer-linux/issues/122#issuecomment-216916197>
>



-- 
With best regards,
Alexander Trufanov

**Comment by whoozle** [comment]
Thank you for your time!
