### ISSUE TITLE
Заливает обрезанные файлы

### ISSUE THREAD

**Issue by p166** [whoozle/android-file-transfer-linux#123]
Прогресс при  копировании доходит до 100%, но файлы не записываются или оказываются обрезанными.

```
upload worker started 
device found, opening session... 
device info "Xiaomi"   "Mi-4c" 
switching to storage id  65537 
session opened, starting 
uploadFiles  ("/home/xxx/ELM327/Torque_1.8.41.apk") 
uploading 5828212 bytes 
uploading file  "/home/xxx/ELM327/Torque_1.8.41.apk" 
uploadFile  "Torque_1.8.41.apk"  as  "Torque_1.8.41.apk" 
sending  5828212  bytes 
new object id:  27110 , sending... 
30015 ms since the last poll call
uploading file  "/home/xxx/ELM327/Torque_1.8.41.apk"  failed:  "timeout reaping usb urb" 
finishing queue 
drop message 0003, response: 2001, transaction: 00000079, transaction: 0000007a
30030 ms since the last poll call
finalizing commands failed:  "timeout reaping usb urb" 
finished 
```

Linux 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Версия aft - git 10/05/2016.

Что осталось в телефоне: [http://pixs.ru/showimage/Screenshot_7923036_21876196.png](http://pixs.ru/showimage/Screenshot_7923036_21876196.png)

**Comment by whoozle** [comment]
причем, по таймауту пришло сообщение что всё ок. :)
я уже видел такое поведение ядра, к сожалению, я не знаю что с этим делать. Похоже никто не чинит баги синхронного апи в ядре. :(

**Comment by whoozle** [comment]
А, я даже переделал на NDELAY + poll. 
А это master? скажите git status пожалуйста

**Comment by p166** [comment]
```
git status
На ветке master
Ваша ветка обновлена в соответствии с «origin/master».
```
А на каком ядре гарантированно работает?

**Comment by whoozle** [comment]
Я не знаю,  к сожалению. Там симптомы всегда одинаковые. Случается таймаут, а потом приходят данные. Может я чего-то не знаю про usb, на самом деле. 

Если вам несложно, давайте проведем эксперимент. Соберите fuse wrapper и попробуйте залить им.

**Comment by p166** [comment]
fuse wrapper это что? aft-mtp-mount?  
//можно в скайп: vestnik.p4

**Comment by whoozle** [comment]
не могли бы вы проверить с текущим master?

**Comment by whoozle** [comment]
И, да, попробуйте поменять кабель. Плохие кабели с дребезгом контактов часто приводят к подобным проблемам. USB очень тупой и не содержит вообще никаких средств обнаружения проблем.

**Comment by hartwork** [comment]
Can the title of this ticket please be renamed to something English so it is clear what one may be missing out on here or not? Thanks!

**Comment by vladimir-menshakov-red** [comment]
@hartwork don't hesitate to open new issue if you feel like it! this looks like duplicate of #91 and no feedback for a long time

**Comment by whoozle** [comment]
@hartwork  don't hesitate to open new issue if you feel like it! 
this looks like duplicate of #91 and no feedback for a long time
