### ISSUE TITLE
"Upload Progress" is shown when files are downloaded

### ISSUE THREAD

**Issue by dschmidt** [whoozle/android-file-transfer-linux#127]
Hey,

I just clicked "Download" on a folder and the window that popped up has "Upload Progress" as window title. Obviously a nitpick :)

BR,
Dominik

P.S.: Thanks for this software, dolphin simply wasn't able to download my huge picture folder - aftl worked like a charm

**Comment by whoozle** [comment]
fixed in 6c6b720692705aab0253dcccaab78b7ca4289c96,
thanks for feedback ! :+1:

**Comment by dschmidt** [comment]
That was quick - great!
