### ISSUE TITLE
v3.0: is already used by another process

### ISSUE THREAD

**Issue by romale** [whoozle/android-file-transfer-linux#129]
Phone: Acer Z630
Android: 5.1
Desktop: Opensuse 13.1 x86_64

android-file-transfer-linux-3.0/build$ **./fuse/aft-mtp-mount ~/my-device**

android-file-transfer-linux-3.0/build$ **l ~/my-device**
итого 16
drwxr-xr-x    0 root   root       0 авг 12 11:10 ./
drwx--x---+ 158 username username 16384 авг 12 11:04 ../
drwxr-xr-x    0 root   root       0 авг 12 11:10 Память телефона/

android-file-transfer-linux-3.0/build$ **./qt/android-file-transfer**
upload worker started 
Device::FindDevice is already used by another process
Device::FindDevice is already used by another process
Device::FindDevice is already used by another process

Qt Error:
"Не найдено ни одного устройства MTP"

**Comment by whoozle** [comment]
MTP эксклюзивный протокол, и вы можете использовать либо fuse, либо android-file-transfer, на выбор, что вам больше нравится.

**Comment by whoozle** [comment]
По идее конечно можно сделать процесс, который будет обслуживать mtp на уровне системы, но тогда все остальные должны уметь с ним работать, и концептуально это очень похоже на fuse :P

**Comment by nekromant** [comment]
@whoozle Насколько знаю, claim_interface это опциональная блокировка, реализованная на уровне libusb (В стандарте USB про него ничего нет). Более того, использование интерфейса без claim'а допустимо.

**Comment by whoozle** [comment]
да, но есть нюанс, -- usbcore пишет в dmesg ошибку при любом обращении к интерфейсу :)

**Comment by whoozle** [comment]
```реализованная на уровне libusb```
я не использую libusb. это блокировка в ядре, и она нужна, потому что usb эксклюзивно должен использоваться, как я понимаю.

**Comment by nekromant** [comment]
Да, я имел в виду ядро, просто на тот момент был не в очень живом и адекватном состоянии ;)

Я предлагаю эту блокировку игнорировать по флажку из командной строки. По опыту могу сказать, что так можно. ( Собственно, на том, что эту проверку можно игнорировать работает вот это: https://github.com/nekromant/pl2303gpio )

**Comment by whoozle** [comment]
я добавил опцию -C в cli/fuse враппер, не могли бы вы посмотреть, как это работает, если всё ок, то я буду добавлять в ui
