### ISSUE TITLE
FIle downloading issue

### ISSUE THREAD

**Issue by trufanov-nok** [whoozle/android-file-transfer-linux#13]
I've tried to download previously uploaded photo and got it back broken. The console: 
```
downloading to  "/home/truf/Изображения" 
downloading  14 to "/home/truf/Изображения/marceline_final_lr_by_artgerm-d7pvus5.jpg" 
progress size 398504 
finished 
```
The reported file size is correct. Files could be downloaded [here](https://yadi.sk/d/fA4L8xInffusb). It's clear that broken file has some byte ordering issues at the end.

**Comment by whoozle** [comment]
The zip file you sent me does not open, says something about missing central signature.

**Comment by trufanov-nok** [comment]
Try these:
http://www.filedropper.com/marcelinefinallrbyartgerm-d7pvus5
http://www.filedropper.com/marcelinefinallrbyartgerm-d7pvus5broken

**Comment by whoozle** [comment]
Looks like your device has failed in attempt to rewrite some exif tags or something (resulting file is missing some bytes in header)

**Comment by trufanov-nok** [comment]
If I recall right the image could be opened on device, so I assume its exif is ok there. The problem appeared when I downloaded file from phone to my laptop to an empty folder. I immediately found the problem as file browser failed to show me preview of this picture.

**Comment by trufanov-nok** [comment]
I was wrong, the jpegs are damaged while uploading, so perhaps it's device dependant indeed.
I also found out that I can't delete anything: `DeleteObject: invalid response code InvalidParameter (0x201d)`

**Comment by trufanov-nok** [comment]
And I tried to upload/download a plain text file and got back a file of a right size but filled with zero bytes.
```
uploadFiles  ("/home/truf/cards.R")
uploading file  "/home/truf/cards.R"
uploadFile  "cards.R"  as  "cards.R"
sending  871  bytes
new object id:  2933 , sending...
ok
progress size 871
finished
downloading to  "/home/truf/Изображения"
downloading  2933 to "/home/truf/Изображения/cards.R"
progress size 871
```

**Comment by whoozle** [comment]
Is it still an issue for you?

**Comment by trufanov-nok** [comment]
Looks like it's fixed now.

**Comment by whoozle** [comment]
feel free to report any new issues you'll find :)
