### ISSUE TITLE
Multiple devices handling

### ISSUE THREAD

**Issue by nekromant** [whoozle/android-file-transfer-linux#131]
Right now aft picks the first device it's able to use and lives with that. Are there any plans to add handling/selection of multiple devices?

**Comment by whoozle** [comment]
yeah, it's planned in 3.1, but I can't seem to find issue right now. :)

**Comment by woky** [comment]
Suggestion: Device identifier could be picked by an environment variable (e.g. AFT_DEVICE). I don't know this identifier should be though.

**Comment by whoozle** [comment]
1. add device model/chooser for qt UI. 
2. mtp mount might display devices as part of file hierarchy, e.g. mount/Nexus5/ and README explaining what to do if you couldn't see any. 
3. cli could display devices as part of hierarchy as fuse does. 

that was the plan originally.

**Comment by volkov0aa** [comment]
It would be simpler to implement mounting of different devices by separated instances of aft-mtp-mount.

**Comment by whoozle** [comment]
add -d/-D command line switches for cli/fuse and DevicesDialog in QT GUI
