### ISSUE TITLE
No recursion (nested folders) when uploading

### ISSUE THREAD

**Issue by taimooryc** [whoozle/android-file-transfer-linux#133]
Let's say you have this folder:

sample/
├── f1
│   ├── music.mp3
│   └── notes.txt
├── f2
│   └── meme.jpg
└── f3
    └── essay.doc

And you try to do an UploadDirectory and select the 'sample' folder, the folders f1, f2, and f3 (and of course the files inside) are ignored, so you have to select them one by one

**Comment by whoozle** [comment]
Can you start application from console and send logs here?

**Comment by taimooryc** [comment]
FolderToUpload/
├── NestedFolder1
│   └── Hello.txt
├── NestedFolder2
│   └── World.txt
└── Notes.txt

Output:

`taimoor@t420:~$ android-file-transfer 
upload worker started
device found, opening session...
device info "OnePlus"   "ONE A2005"
switching to storage id  65537
session opened, starting
uploadFiles  ("/home/taimoor/FolderToUpload")
adding subdirectory "/home/taimoor/FolderToUpload"
uploading 24 bytes
making directory "/home/taimoor/FolderToUpload"
parent:  "/home/taimoor/FolderToUpload" , dir:  "FolderToUpload"
uploading file  "/home/taimoor/FolderToUpload/Notes.txt"
uploadFile  "Notes.txt"  as  "Notes.txt"
sending  12  bytes
new object id:  5805 , sending...
ok
making directory "/home/taimoor/FolderToUpload/NestedFolder1"
parent:  "/home/taimoor/FolderToUpload/NestedFolder1" , dir:  "NestedFolder1"
uploading file  "/home/taimoor/FolderToUpload/NestedFolder1/Hello.txt"
uploadFile  "Hello.txt"  as  "Hello.txt"
sending  6  bytes
new object id:  5807 , sending...
ok
making directory "/home/taimoor/FolderToUpload/NestedFolder2"
parent:  "/home/taimoor/FolderToUpload/NestedFolder2" , dir:  "NestedFolder2"
uploading file  "/home/taimoor/FolderToUpload/NestedFolder2/World.txt"
uploadFile  "World.txt"  as  "World.txt"
sending  6  bytes
new object id:  5809 , sending...
ok
finishing queue
finished
`

[Here's what is uploaded (Notes.txt is uploaded, but NestedFolder1 and 2 and their files are not.)](http://i.imgur.com/sBguYN3.png)

**Comment by whoozle** [comment]
do this files appear if you restart AFS? 
what phone do you have?

**Comment by whoozle** [comment]
Should be fixed in 3eb5268583169a3fba46cbc19c8d276d8af8a05a
