### ISSUE TITLE
My dmg file can't work well in different version of OS X.

### ISSUE THREAD

**Issue by weurany** [whoozle/android-file-transfer-linux#135]
Hi,
   I build the dmg file in OS X 10.11.6, and when we run the dmg in OS X 10.10.3 and 10.9.6, the dmg can't work well , it's said the version of OS X is not match with the application, can you help to check this problem?

**Comment by whoozle** [comment]
probably you need to put all libraries and framework there, refer to qt/mac os x documentation. 

This it good place to start:
http://doc.qt.io/qt-5/osx-deployment.html
