### ISSUE TITLE
Replacing existing file UX

### ISSUE THREAD

**Issue by trufanov-nok** [whoozle/android-file-transfer-linux#14]
Regarding file uploading I would like to note that if you try to upload a file which already exist on device you'll get no warnings in GUI and this in console output:
```
uploading file  "/home/truf/Изображения/wallp/marceline_final_lr_by_artgerm-d7pvus5.jpg"
  failed:  SendObjectInfo: invalid response code InvalidParameter (0x201d) 
progress size 398504 
finished 
```

Would be great if GUI user will be informed.

**Comment by whoozle** [comment]
fixed in 43cfb06ebfa15533a623a5a42432c505c8b146e6
