### ISSUE TITLE
macOS binaries

### ISSUE THREAD

**Issue by AAS** [whoozle/android-file-transfer-linux#140]
Hi guys!

Could you please build a macOS binaries and attach them to the releases page?

On mac it's uncommon to build your software on your own and have to download, compile and setup all the requirements before that (I personally believe installing gigantic qt sources on mac is a no go to try a software).

Plus, when you do that, the binaries could be added to [homebrew-cask](https://github.com/caskroom/homebrew-cask) and they could be installed with just one terminal command.

**Comment by whoozle** [comment]
Hello, sorry for late reply. 
Unfortunately I don't have any mac hardware nor intention to buy it. 
If someone was able to donate any old used Mac Mini (or new shiny lol), I would gladly polish and publish everything on mac. 

If you know any remote-accessible public build farms with ssh access, please point me in right direction.

**Comment by JeremyLaurenson** [comment]
I can build the Disk Image for you, if that works for you for the moment

**Comment by whoozle** [comment]
Basically I don't have anyone who can build mac os x images each release, and I have no hardware to test on. Mac port was made using ssh and @gazay's macbook lol 💃 
If you can spare some of your time to do it, you'll be great help!

**Comment by JeremyLaurenson** [comment]
[Android File Transfer.dmg.zip](https://github.com/whoozle/android-file-transfer-linux/files/822561/Android.File.Transfer.dmg.zip)

**Comment by JeremyLaurenson** [comment]
@whoozle if you have some ftp/sftp site available I can add a step in my build script to take the Mac .DMG package and simply upload it each build.

**Comment by JeremyLaurenson** [comment]
This DMG will work on OS X 10.8.5 or above.

[Android File Transfer.dmg.zip](https://github.com/whoozle/android-file-transfer-linux/files/828404/Android.File.Transfer.dmg.zip)

**Comment by whoozle** [comment]
I think you can bundle qt framework in dmg installer, I did it with SDL/other libs before

**Comment by JeremyLaurenson** [comment]
I have never worked with this stuff before (I do development on OS X inside Apple's own environment) 

I'll mess around and see what I can find

**Comment by JeremyLaurenson** [comment]
Done. I have a complete pipeline to generate a DMG with EULA as well as packaged AFT OS X. Now where to put it. @whoozle what works best do get the image onto this site, or do you want to link to it?

**Comment by JeremyLaurenson** [comment]
[AndroidFileTransferOSX.dmg.zip](https://github.com/whoozle/android-file-transfer-linux/files/831389/AndroidFileTransferOSX.dmg.zip)

**Comment by whoozle** [comment]
I can make you a collaborator, so you can attach dmg files to release yourself, how does it sound?

**Comment by whoozle** [comment]
you can skip zipping of dmg, dmg is already compressed, there's no significant difference between zipped/unzipped versions

**Comment by JeremyLaurenson** [comment]
Github wouldn't allow to upload .dmg I can certainly attach the builds.

**Comment by whoozle** [comment]
fine, here's your invitation! :)
https://github.com/whoozle/android-file-transfer-linux/invitations

**Comment by whoozle** [comment]
btw, github possibly allows attaching dmg to release pages, it's more or less reasonable to not allow attaching executable in public issues.

**Comment by JeremyLaurenson** [comment]
Yes. Done!

**Comment by whoozle** [comment]
thanks a lot!
