### ISSUE TITLE
Can not change active storage in cli

### ISSUE THREAD

**Issue by JeremyLaurenson** [whoozle/android-file-transfer-linux#144]
Please add a command to change storage location in the cli. Currently it looks like it defaults to "all" which according to the GUI is "Buggy" :-)

**Comment by whoozle** [comment]
basically, mtp standard tells that uploading file to 'all' storages allows device to pick up best storage for it, but in reality some devices hide files between 'all' and non-'all' modes

please find revision 99f658ac74c11dadc78db9b94cb700217f6c9b17, I've added 'storage' command with auto-completion, ('All'/'all'/'*' should work as alias to all)

**Comment by JeremyLaurenson** [comment]
No juice:
```
O&P Innovations DP-X1 1.0
extensions: microsoft.com: 1.0; android.com: 1.0;
O&P Innovations DP-X1> storage-list
196609   volume: , description: SD card 2
65537    volume: , description: Internal storage
131073   volume: , description: SD card 1
O&P Innovations DP-X1> storage 196609
selected storage 196609  SD card 2
error: storage 196609 could not be found
O&P Innovations DP-X1:SD card 2> storage "SD card 2"
selected storage 196609  SD card 2
error: storage SD card 2 could not be found
O&P Innovations DP-X1:SD card 2> quit
```

**Comment by JeremyLaurenson** [comment]
Interestingly the prompt shows the new storage, but actions show all:

`454402     Haq.mp4
454405     usbSharer
O&P Innovations DP-X1:SD card 1> storage "131073"
selected storage 131073  SD card 1
error: storage 131073 could not be found
O&P Innovations DP-X1:SD card 1> ls
1          Music
2          Podcasts
3          Ringtones
4          Alarms
5          Notifications
6          Pictures
7          Movies
8          Download
9          DCIM
10         Android
8396       e-onkyo music
28287      .estrongs
28291      backups
28295      dianxin
32004      .userReturn
74206      Onkyo
212259     storage
252596     .DS_Store
286191     .metadata_never_index
381926     vysor
390102     gmmp
398138     com.kingroot.kinguser
398139     toprange
398141     tencent
398144     kinguserdown
398287     krsdk-b105006-stock-conf
398292     com.kingstudio.purify
398293     KingMaster
399469     .profile
446779     Music
453897     Playlists
453900     Android
453923     .Spotlight-V100
453939     The Long Version.mp4
453940     Man of Steel.m4v
453941     Suddenly I See (Original 1080p).mp4
453942     In The Beginning.m4v
453943     03 Suddenly I See (Final 640x360).mp4
453944     Rodriguez - Crucify Your Mind live Wexner Center 11.1.12.mp4
454173     .metadata_never_index
454391     MQATests
454401     ._Haq.mp4
454402     Haq.mp4
454405     usbSharer
O&P Innovations DP-X1:SD card 1> 
O&P Innovations DP-X1:SD card 1> ls
`

**Comment by JeremyLaurenson** [comment]
Interestingly the prompt shows the new storage, but actions show all:

```
454402     Haq.mp4
454405     usbSharer
O&P Innovations DP-X1:SD card 1> storage "131073"
selected storage 131073  SD card 1
error: storage 131073 could not be found
O&P Innovations DP-X1:SD card 1> ls
1          Music
2          Podcasts
3          Ringtones
4          Alarms
5          Notifications
6          Pictures
7          Movies
8          Download
9          DCIM
10         Android
8396       e-onkyo music
28287      .estrongs
28291      backups
28295      dianxin
32004      .userReturn
74206      Onkyo
212259     storage
252596     .DS_Store
286191     .metadata_never_index
381926     vysor
390102     gmmp
398138     com.kingroot.kinguser
398139     toprange
398141     tencent
398144     kinguserdown
398287     krsdk-b105006-stock-conf
398292     com.kingstudio.purify
398293     KingMaster
399469     .profile
446779     Music
453897     Playlists
453900     Android
453923     .Spotlight-V100
453939     The Long Version.mp4
453940     Man of Steel.m4v
453941     Suddenly I See (Original 1080p).mp4
453942     In The Beginning.m4v
453943     03 Suddenly I See (Final 640x360).mp4
453944     Rodriguez - Crucify Your Mind live Wexner Center 11.1.12.mp4
454173     .metadata_never_index
454391     MQATests
454401     ._Haq.mp4
454402     Haq.mp4
454405     usbSharer
O&P Innovations DP-X1:SD card 1> 
O&P Innovations DP-X1:SD card 1> ls
```

**Comment by whoozle** [comment]
ops, I put throw and forget to replace break with return, 
fixed in 7c0c132fed3e48330dee0dd8c91b678f6dc53cf9

**Comment by whoozle** [comment]
you can use either numeric id from storage-list or its name. For some reason readline does not work well with spaces (or I don't work with spaces well), I will look into it

**Comment by whoozle** [comment]
escaping fixed in 49a75e1c11c3d0357212b8863c795b07dc3c1b5a

**Comment by probonopd** [comment]
How can we explicitly upload to the SD card in the GUI? It only shows me "internal shared memory" and "ALL (buggy)" but not "SD Card".

**Comment by whoozle** [comment]
Can you type storage-list in cli? Is there any difference? "Internal memory" is something device sent to you, so it may be your device who blocks the access

**Comment by probonopd** [comment]
I reformatted the SD card as "external", now I can select the SD card. So maybe this is an Android thing.

**Comment by whoozle** [comment]
yes, it's most likely. Neither MTP nor I don't make any assumptions on what storages were present or what are their names . Also, in newer android, empty storage list means that device is blocking file transfers until user explicitly allowed them (usb charging → file transfer in popup menu).
