### ISSUE TITLE
put with path to create the path as well

### ISSUE THREAD

**Issue by JeremyLaurenson** [whoozle/android-file-transfer-linux#146]
I am using the CLI app to copy music over to a device, but there is a significant amount of work involved in figuring out and creating intermediate directory structures.

For example, I would like to be able to say:

`put /source/music/artist/album/originalfilename.mp3 /Music/Artist/Album/NewFileName.mp3`

in order to create destination directories, and copy the file there with new destination name.

This solves some issues I have:
1. Make intermediate directories is very difficult because it has to be done a level at a time, and also needs to check for existing directories. The app throws errors and exits if I try do it all in one:

`"storage 3489726465" "mkdir Music" "cd Music" "mkdir Xtc" "cd Xtc" "mkdir Skylarking" "cd Skylarking" "put /Users/jeremylaurenson/Music/Tiny\ Media/Music/XTC/Skylarking/12\ Dear\ God.m4a"
`
2. To change file names for conversion, I have to rename the original, copy and then rename back,

As-is I call the cli and have to make 5 or 6 calls to copy a file in order to check/make directories.

**Comment by JeremyLaurenson** [comment]
I need more granularity because often I have the case where deltas are to be uploaded. For example a freshly tagged track, or album art file for existing content.

An interim option for me in the mean time may be a flag on `mkdir` that ignores the error thrown if the directory exists already. This way I can simply mkdir/cd through to the file location and do a simple put.

Ultimately the optimal for me would be the original case:

`aft-mtp-cli "storage 3489726465" "put /source/music/artist/album/originalfilename.mp3 /Music/Artist/Album/NewFileName.mp3"`

A flag would help me brute force it:
`aft-mtp-cli "storage 3489726465" "mkdir -f Music" "cd Music" "mkdir -f Xtc" "cd Xtc" "mkdir -f Skylarking" "cd Skylarking" "put /Users/jeremylaurenson/Music/Tiny\ Media/Music/XTC/Skylarking/12\ Dear\ God.m4a"`

**Comment by whoozle** [comment]
I'm thinking of different command similar to python's mkpath, it just creates missing directories, so you can just ensure that all path to specific directory exists, e.g. ```mkpath Music/XTC/Skylarking```

I'm sure we can figure something out, but you can fork/use code in the ways GPL allowed you to do, I'm happy to see some spin-offs really. But I don't feel that current state of cli tool is robust enough, so I can improve it eventually.

**Comment by whoozle** [comment]
So, let's imagine mkpath is implemented and works well, what else do you need? I mean, could it be some sort of sync command, which uploads newer files in directories? 

I'm also thinking of wrapping all functionality in python module, so you can just script your jobs in python instead of fiddling with some obscure ftp-like cli tool

**Comment by JeremyLaurenson** [comment]
I think that's all I would need. It'd be nice to put a file with a destination file name but it's not a blocker

**Comment by JeremyLaurenson** [comment]
I think that's all I would need. It'd be nice to put a file with a destination file name but it's not a blocker.
 I actually recursively read the full storage to make choices about new uploads. It'd be nice to just dump all files on a storage with paths.

**Comment by JeremyLaurenson** [comment]
I suppose I should be clear what I am doing:

I am using this to gather a full inventory on whats on the Android device.
(I have it `ls` ing and then for each directory I `cd` into the directory and `ls` again recursively)

The result is that I I build a full inventory of files including sizes and dates
(A `lsall` with the full lsext info for every object on the storage would be massively helpful, but not required)

Then I compare that with whats on the OS X machine, and build a diff list.

I then execute the copy function per file that needs to be uploaded/replaced and here is where the multiple nested directories would help a ton, as would a copy routine that forced an overwrite.

I will also do a delete function, but that recursively deletes so that as fine.

J

**Comment by whoozle** [comment]
so, ideally, we can have mkpath, recursive version of ls/lsext, and put <file> <dir/file> variant.

**Comment by JeremyLaurenson** [comment]
Exactly.

You could bundle up the whole make path/put  thing in a super put

**Comment by whoozle** [comment]
added ls-r/lsext-r commands, please check them out while I'm working on mkpath/better put. :)
(they should use current storage)

**Comment by whoozle** [comment]
what do you think will be better: 
1. process directory as soon I see them, e.g.
a/ a/b/1 a/b/2 b c
2. process directories after current
a b c a/b a/b/1 b/b2

**Comment by JeremyLaurenson** [comment]
1

**Comment by JeremyLaurenson** [comment]
Need to be able to see the path in the lsext-r  Right now it shows:
`
7254       3489726465 3001      32768 2017-03-07 13:41:48 LOST.DIR 0x0 
7255       3489726465 3001      32768 2017-03-07 13:41:48 Android 0x0 
7258       3489726465 3001      32768 2017-03-07 13:41:48 files 0x0 
7265       3489726465 3001      32768 2017-03-07 13:41:48 Download 0x0 
7266       3489726465 3001      32768 2017-03-07 13:41:48 Movies 0x0 
7267       3489726465 3001      32768 2017-03-07 13:41:48 Music 0x0 
7795       3489726465 3001      32768 2017-03-07 16:41:20 A-Ha 0x0 
7796       3489726465 3001      32768 2017-03-07 16:41:33 25 Deluxe Version 0x0 
7797       3489726465 300b    9165557 2017-03-07 16:41:57 29 Velvet.m4a 0x0 
`

I would need to see:

`
7254   3001      32768 2017-03-07 13:41:48 /3489726465/LOST.DIR 0x0 
7255   3001      32768 2017-03-07 13:41:48 /3489726465/Android 0x0 
7258   3001      32768 2017-03-07 13:41:48 /3489726465/files 0x0 
7265   3001      32768 2017-03-07 13:41:48 /3489726465/Download 0x0 
7266   3001      32768 2017-03-07 13:41:48 /3489726465/Movies 0x0 
7267   3001      32768 2017-03-07 13:41:48 /3489726465/Music 0x0 
7268   3001      32768 2017-03-07 13:41:48 /3489726465Notifications 0x0 
7269   3001      32768 2017-03-07 13:41:48 /3489726465Pictures 0x0 
7795   3001      32768 2017-03-07 16:41:20 /3489726465//Music/A-Ha 0x0 
7796   3001      32768 2017-03-07 16:41:33 /3489726465//Music/A-Ha/25 Deluxe Version 0x0 
7797   300b    9165557 2017-03-07 16:41:57 /3489726465//Music/A-Ha/29 Velvet.m4a 0x0 
`

**Comment by whoozle** [comment]
I found and fixed it already :) a13e07ac38015e5cc31059c77aaf1269660778e9

**Comment by JeremyLaurenson** [comment]
Luckily I have a pull-build-run script :-)

**Comment by JeremyLaurenson** [comment]
Sweet  much better - still not stacking all the directories:

```
7794       3489726465 3001      32768 2017-03-07 16:38:25 Music 
7795       3489726465 3001      32768 2017-03-07 16:41:20 Music/A-Ha 
7796       3489726465 3001      32768 2017-03-07 16:41:33 A-Ha/25 Deluxe Version 
7797       3489726465 300b    9165557 2017-03-07 16:41:57 25 Deluxe Version/29 Velvet.m4a 
```

**Comment by whoozle** [comment]
ops, added two lines and two new bugs :D

**Comment by whoozle** [comment]
please check 792829dca89ade03d1e63cf30d4ac53fb83ac60f

**Comment by JeremyLaurenson** [comment]
Perfect

**Comment by whoozle** [comment]
I implemented both put <src> and put <src> <dst> commands

put <file> <file in existing path> will rename file, just like cp does.

**Comment by JeremyLaurenson** [comment]
Is there a -f style option?

**Comment by JeremyLaurenson** [comment]
I am able to:

- List all files
- Create a full path
- Copy a file to new location with new name

So I consider this request closed - thank you :-)
