### ISSUE TITLE
Please enable basic information for connected device in cli

### ISSUE THREAD

**Issue by JeremyLaurenson** [whoozle/android-file-transfer-linux#147]
I would like to see a cli based stat command to see:

Per-storage storage size and storage in use
https://developer.android.com/reference/android/mtp/MtpStorageInfo.html

```
final long	getFreeSpace()
Returns the amount of free space in the storage unit in bytes
final long	getMaxCapacity()
Returns the maximum storage capacity for the storage unit in bytes
```

Device info: https://developer.android.com/reference/android/mtp/MtpDeviceInfo.html
```

final String	getManufacturer()
Returns the manufacturer's name for the MTP device
final String	getModel()
Returns the model name for the MTP device
final String	getSerialNumber()
Returns the unique serial number for the MTP device

```

I think at that point I will be done :-)

**Comment by whoozle** [comment]
```
➜  android-file-transfer-linux git:(master) ✗ ./build/cli/aft-mtp-cli 'device-info'
LGE
Nexus 5
1.0
****************
microsoft.com: 1.0; android.com: 1.0;
```

0b6e058df642888afe55fc574bb5791080cc0f6c

**Comment by whoozle** [comment]
storage-info added in 7f39c4dba35694b95e9becdc5004d75c9698361c

**Comment by JeremyLaurenson** [comment]
Perfect - I am all done - thanks very much for all your help, very much appreciated!
