### ISSUE TITLE
Improve navigation in GUI

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#148]
Right now there are keyboard shortcuts Ctrl-R to reread and Alt-Up for going one level up. Could you also add toolbar buttons for those operations? Or at least menu item for level up?

**Comment by whoozle** [comment]
fixed in acada052c6646a0eaf671067c627ce25da30d787

**Comment by whoozle** [comment]
top-left button is 'back', I've added refresh action to toolbar too.
