### ISSUE TITLE
Some types of Android devices do not show file dates

### ISSUE THREAD

**Issue by JeremyLaurenson** [whoozle/android-file-transfer-linux#151]
Hi!

If I do an lsext on some devices the listing excludes dates, which breaks my parser:

New device:
```
422        131073     3001     131072  Black Eyed Peas 
423        131073     3001     131072  Fergie 
424        131073     3001     131072  Iem Bass Test 
425        131073     3001     131072  Music From The Motion Picture Fred Claus 
426        131073     3001     131072  Johnny Clegg & Juluka 
427        131073     3001     131072  Koos Kombuis 
428        131073     3001     131072  LOST.DIR

```

Normal device:
```
509118     196609     300b   89515703 2017-03-11 19:24:05 In The Beginning.m4v 
509119     196609     300b   64531319 2017-03-11 19:24:05 03 Suddenly I See (Final 640x360).mp4 
509120     196609     300b   21546717 2017-03-11 19:24:05 Rodriguez - Crucify Your Mind live Wexner Center 11.1.12.mp4 
509350     131073     3000          0 2017-03-11 19:24:07 .metadata_never_index 
509412     196609     3004         29 2017-03-11 19:24:07 date.txt
```

I think we need a way to normalize the listings - I also see that in some cases storageID or fileID can exceed 10 characters.

Maybe we can use Tabs between fields. Or have a mode to set which will switch to tab separated fields lsext

In addition, if you include a header line the parser can use that to determine what field is where so that if later you add a field, it doesnt need to be redone:

```
lsmode t
lsext-r
storageid itemid type size date time filename
50911 8196609 300b 89515703 2017-03-11 19:24:05 In The Beginning.m4v 
509119 196609 300b 64531319 2017-03-11 19:24:05 03 Suddenly I See (Final 640x360).mp4 
509120 196609 300b 21546717 2017-03-11 19:24:05 Rodriguez - Crucify Your Mind live Wexner 
```

**Comment by whoozle** [comment]
How do you parse this data? I don't think fine-tuning formatting is good way to integrate things, really. I agree on displaying invalid date and header line though. 

Can you just split('\w+') or something?

**Comment by whoozle** [comment]
Can you use libmtp-ng directly? I had plans to change license to LGPL for library, probably it's good time to do it :)

**Comment by JeremyLaurenson** [comment]
I can certainly split that way - the missing data is the largest issue. :-)

**Comment by JeremyLaurenson** [comment]
Let me see if I can figure out libmtp-ng as well..

**Comment by whoozle** [comment]
it should be easy, you call Device::Find and get the list of device descriptions, then obtain session with OpenSession(1), the rest is pretty self-explanatory. 

btw, I added date output in 992f234cafecd9a9b24fca3bc3e7ce056bab805b

**Comment by JeremyLaurenson** [comment]
Thanks!
