### ISSUE TITLE
Please add percentage progress to put/get in cli output when not interactive

### ISSUE THREAD

**Issue by JeremyLaurenson** [whoozle/android-file-transfer-linux#155]
I would like to be able to see progress when put/getting using cli non interactive as this is a good way to tell if the command is stalled. Simple %age output would be great

Same stream as the standard output for commands like storage-list

**Comment by JeremyLaurenson** [comment]
```
rtp-jlaurens-8818:Back in Black jeremylaurenson$ ./aft-mtp-cli "put 01\ Hells\ Bells.m4a"
Device::Findvector
Device::Findvector
0
1
2
3
4
5
6
7
8
9
....
99
100
rtp-jlaurens-8818:Back in Black jeremylaurenson$ 

```

**Comment by whoozle** [comment]
Ops, I missed it somehow, so sorry, I'll add it, can we add some special character, e.g. # to separate regular output from progress and other stuff? Is it ok for you?

**Comment by whoozle** [comment]
#10% 
#11% 
etc

**Comment by JeremyLaurenson** [comment]
That works fine for me. Thanks

**Comment by whoozle** [comment]
added -e/--events option, allowing you to get progress and "command finished" events from stdout
