### ISSUE TITLE
App hangs for a long time after uploading .m3u playlists

### ISSUE THREAD

**Issue by JeremyLaurenson** [whoozle/android-file-transfer-linux#156]
It seems like on these types of files the app is blocked after uploading, by the device itself, for a fair amount of time (presumably while it checks the file?)

Is this bad behavior on the part of the android device? Normal?

![screen shot 2017-03-22 at 4 26 11 pm](https://cloud.githubusercontent.com/assets/942556/24219184/4d4bc24a-0f1c-11e7-9db5-d86cc06cf98d.png)

**Comment by JeremyLaurenson** [comment]
https://www.youtube.com/watch?v=iourNjRBPeA&feature=youtu.be

**Comment by whoozle** [comment]
Thanks, so it looks like android quirk!
