### ISSUE TITLE
Add python bindings

### ISSUE THREAD

**Issue by whoozle** [whoozle/android-file-transfer-linux#161]

**Comment by alex3kov** [comment]
What are the chances of this happening? Can you add only a `mount` binding for a start?

**Comment by whoozle** [comment]
could be easily done with SWIG actually :)

**Comment by whoozle** [comment]
Started working on python-module branch. I have to remember how to use that bloody SWIG, it's so convoluted.
https://github.com/whoozle/android-file-transfer-linux/tree/python-module

**Comment by whoozle** [comment]
it looks like SWIG is still rubbish as it was before, no nested structures, no native with() integration, convoluted pointers, it looks like I have to use different tool for this

**Comment by whoozle** [comment]
actually I was able to create wrapper around device, but shared_ptr hell made me give up lol

**Comment by whoozle** [comment]
python binding added in `v4.0`
