### ISSUE TITLE
Add Smart-Switch-Like Features

### ISSUE THREAD

**Issue by HarvHouHacker** [whoozle/android-file-transfer-linux#167]
I'm an avid Ubuntu user, but my Galaxy S7 Edge is rooted and Smart Switch requires Windows or Mac OS X. I ran across your program, hoping it would provide the needed security updates to my existing Android 6.0.1. It works well for transfer, but it doesn't provide updates. Is it possible to be able to get android updates from a future update of this program?

**Comment by whoozle** [comment]
It's some samsung-specific closed and proprietary protocol, if you have any documentation on that or protocol specification, feel free to re-open this ticket.
