### ISSUE TITLE
Icon in the wrong place

### ISSUE THREAD

**Issue by pezcurrel** [whoozle/android-file-transfer-linux#170]
Just a little aesthetic issue :) ... AFT package has its icon set up as...
`/usr/share/icons/hicolor/128x128/apps/android-file-transfer.png`
...but since it's a 512x512px image, it shows way too big in xfce's menus.
It would be good if it was set up as...
`/usr/share/icons/hicolor/512x512/apps/android-file-transfer.png`

**Comment by seaninspace** [comment]
#173 <- Hopefully this fixes it :)
