### ISSUE TITLE
Appimage for Linux distribution

### ISSUE THREAD

**Issue by philipzae** [whoozle/android-file-transfer-linux#171]
Would be great if you could provide a binary build in appimage format for linux users so they dont have to compile releases from source. Apps like Krita, Kdenlive, and OpenShot do so.

You can find information about how to do so here - https://github.com/AppImage/AppImageKit/

**Comment by philipzae** [comment]
Someone has submitted a pull request for it already it seems.

https://github.com/whoozle/android-file-transfer-linux/pull/172

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by probonopd** [comment]
Please make the AppImage available on [GitHub Releases](https://github.com/whoozle/android-file-transfer-linux/releases). This can be done by setting up the `GITHUB_TOKEN` variable in Travis CI as described in the [uploadtool](https://github.com/probonopd/uploadtool) documentation. Thanks.

![androidfile transfer](https://user-images.githubusercontent.com/2480569/34470680-2b6add2c-ef37-11e7-8e6f-2f096b7ab132.png)

**Comment by whoozle** [comment]
I think I was able to follow that guide of theirs, and thanks to everyone contributed to AFT, all checks have been passed. But in the end, it was not automatically merged. 

Please find my PR there:
https://github.com/AppImage/appimage.github.io/pull/235

**Comment by probonopd** [comment]
Thank you very much. Investigating the AppImageHub issue.

> Old Qt looks really ugly, but it worked for me

For me it is exactly the other way around: New Qt does not seem to follow Gtk+ themes anymore and hence looks ugly... let me know if you know why.

**Comment by whoozle** [comment]
hmmm, as far as I know, plasma/kde is providing their own gtk theme engine, trying to unify look and feel across different toolkits. Maybe this engines are missing from appimage

**Comment by whoozle** [comment]
Could you please take a look into #174 ? I don't have any OSX device to test/build it on. Is there any appimage advantages over dmg?

**Comment by probonopd** [comment]
- AppImages are for Linux
- .dmg files are for macOS

An AppImage is conceptually similar to an .app bundle inside a .dmg disk image on macOS. Technically they have no direct commonalities.
