### ISSUE TITLE
`aft-mtp-mount` always mounts as root

### ISSUE THREAD

**Issue by pavlepredic** [whoozle/android-file-transfer-linux#176]
On my arch linux (kernel: 4.14.12-1-ARCH), I installed `android-file-transfer` and `android-udev` packages. The latter correctly created a udev rule, which plugs my android device with these permissions: 
```crw-rw----+ 1 root adbusers 189, 2 Jan 10 11:34 /dev/bus/usb/001/003```

I added my user to the `adbusers` and can successfully mount the volume (albeit with some error messages such as `Device::FindDevice is already used by another process`), but the directory where it is mounted is owned by root, even though I executed the command as the normal user. Is there anything I can do to make the user that is executing the mount command be the owner of the mounted directory?

BTW, here's the output of `lsusb | grep Moto`: `Bus 001 Device 003: ID 22b8:2e82 Motorola PCS`

**Comment by whoozle** [comment]
you have to run mount under your normal user account, and if it refuses to do it, you have to set up fuse permission, probably by setting suid bit on fusermount3 binary or whatever fuse version you have. (see fuse manual). 
Alternatively try passing '-o user' to aft-fuse-mount

**Comment by pavlepredic** [comment]
I am mounting it as normal user and it mounts it successfully, but it assigns the ownership of the mounted volume to root. I tried passing the `-o user` option, but I'm getting an error: `fuse: unknown option `user'`

**Comment by whoozle** [comment]
argh, it's now ignored by mouse.fuse. Can you try passing 'allow_other' ? at least it will allow user access for root mounts. maybe arch is setting SUID bit for mount.fuse, dunno

**Comment by whoozle** [comment]
@pavlepredic did allow_user help?

**Comment by pavlepredic** [comment]
I didn't try it. I switched to sshfs.

**Comment by maz-1** [comment]
the problem still exists, allow_user does't solve it

**Comment by phunehehe** [comment]
FWIW currently `sudo aft-mtp-mount -o allow_other ~/mtp` works fine for me
