### ISSUE TITLE
"No MTP Device Found"

### ISSUE THREAD

**Issue by steelstring94** [whoozle/android-file-transfer-linux#178]
AFT worked like a charm for me previously, but now I am getting "no MTP device found" even though my device is connected and in MTP mode.  I wish I could provide more details, but as I have no idea what is wrong, I'm not sure where to start.  I will say, I have debugging mode enabled and ADB daemon is running on my PC, but I have tried this with debugging off and it still doesn't work.  I am running Fedora 27 KDE.  I have KDE Connect installed on the phone and it is connected.

**Comment by whoozle** [comment]
could you run ```aft-mtp-cli -v``` please?

**Comment by steelstring94** [comment]
`bash: aft-mtp-cli: command not found`

**Comment by vladimir-menshakov-red** [comment]
can you clone this repo, build it, and run ./build/cli/aft-mtp-cli -v?

**Comment by whoozle** [comment]
can you clone this repo, build it, and run ./build/cli/aft-mtp-cli -v?

**Comment by steelstring94** [comment]
With no device plugged in:

```sh
probing device 29ea:0102
probing device 0d8c:0012
probing device 12c9:102a
no mtp device found
```
With my phone plugged in and USB mode set to Just Charging:

```sh
probing device 22b8:2e76
capabilities = 0x0000007f
page size = 4096
<zero-packet> 
<bulk-continuation> 
<no-packet-size-limit> 
<bulk-scatter-gather> 
<reap-after-disconnect> 
<mmap> 
<drop-privileges> 
Device::Find failed:Device is already used by another process
probing device 29ea:0102
probing device 0d8c:0012
probing device 12c9:102a
no mtp device found
```

With my device plugged in and USB mode set to MTP:

```sh
probing device 22b8:2e76
capabilities = 0x0000007f
page size = 4096
<zero-packet> 
<bulk-continuation> 
<no-packet-size-limit> 
<bulk-scatter-gather> 
<reap-after-disconnect> 
<mmap> 
<drop-privileges> 
Device::Find failed:Device is already used by another process
probing device 29ea:0102
probing device 0d8c:0012
probing device 12c9:102a
no mtp device found
```

**Comment by whoozle** [comment]
can you run ```lsusb``` command too? 
it looks like 22b8:2e76 is your phone, and it's been used by some process.

Can you try figuring out what process is using your usb device? (following steps from faq)
https://github.com/whoozle/android-file-transfer-linux/blob/master/FAQ.md

**Comment by steelstring94** [comment]
It's working now.  I don't know why.  If the problem happens again I will do these steps.  The only major change to my system was an update to KDE 5.12 and kernel 4.15.8.

**Comment by whoozle** [comment]
Sometimes it happens with plasma, thanks for the feedback

**Comment by steelstring94** [comment]
For anyone else who comes across this, in the end it turns out it's Amarok doing it.
