### ISSUE TITLE
uploading m3u playlists

### ISSUE THREAD

**Issue by dnalor** [whoozle/android-file-transfer-linux#180]
I couldn't get m3u playlist files recognized as system playlists in Android (v7.1.2, Resurrection Remix) when uploading them with AFT.
The reason seems to be that they are assigned a mime type of text/plain (instead of application/x-mpegurl) in Android's media storage.

AFT's output confirms this:
```
uploading file  "/home/user/tmp/pls/testplaylist.m3u" , parent:  "/home/user/tmp/pls"
MAGIC MIME: text/plain
```

The first thing I tried was to add the following in ObjectFormat.cpp:
`MAP_TYPE("application/x-mpegurl",	ObjectFormat::M3u);`

which didn't seem to change anything, due to an issue with libmagic's magic database (from file v5.32):
```
$ file testplaylist.m3u 
testplaylist.m3u: M3U playlist, UTF-8 Unicode text
$ file -i testplaylist.m3u
testplaylist.m3u: text/plain; charset=utf-8
```

Changing file-5.32/magic/Magdir/audio fixes this:
```
# .m3u
0	search/1	#EXTM3U 	M3U playlist text
!:mime	application/x-mpegurl
```

```
$ file -i testplaylist.m3u 
testplaylist.m3u: application/x-mpegurl; charset=utf-8
```

and finally the upload works correctly:
```
uploading file  "/home/user/tmp/pls/testplaylist.m3u" , parent:  "/home/user/tmp/pls"
MAGIC MIME: application/x-mpegurl
```
and the file is correctly classified as a playlist on the phone.

**Comment by whoozle** [comment]
Thanks for your thorough examination! 

I've added workaround in ec52ee9ef4a8399ee94158e00935cf4e8385b70a and it seems to work for me.

**Comment by dnalor** [comment]
Tested, and it seems to do the trick. Thanks!

**Comment by whoozle** [comment]
Np, feel free to contact me in case of any problems
