### ISSUE TITLE
Avaibility as a flatpak or snapd package?

### ISSUE THREAD

**Issue by Warmuser** [whoozle/android-file-transfer-linux#186]
Can you release these software as flatpak or snapd package, for those who need uncomplicated installation process? Thanks

**Comment by whoozle** [comment]
nice idea, any PRs are welcome! :smile:

**Comment by whoozle** [comment]
added simple manfiest in c765c8ffaaf92ade9ede56bc760bfa8fb8a6dcf2, not quite finished yet

**Comment by Lin-Buo-Ren** [comment]
FYI: https://github.com/Lin-Buo-Ren/android-file-transfer-linux-snap

**Comment by whoozle** [comment]
https://snapcraft.io/android-file-transfer-linux 
Track flatpack in #218
