### ISSUE TITLE
Xenial doc bug: libfuse-dev

### ISSUE THREAD

**Issue by danbikle** [whoozle/android-file-transfer-linux#187]
I see a problem on my Xenial laptop [ Ubuntu 16.04.3 LTS ]

This shell command gives me a problem:
`
apt-get install build-essential cmake libqt4-dev ninja-build libfuse-dev libreadline-dev
`

I see this problem:
`
libfuse-dev : Depends: libfuse2 (= 2.9.4-1ubuntu3) but 2.9.4-1ubuntu3.1 is to be installed
`

I see this as a documentation bug.

The doc should explain a better way to meet prerequisites.

**Comment by vladimir-menshakov-red** [comment]
Unfortunately, it's Ubuntu problem, libfuse-dev listed wrong version number for its base library package. Usually these problems go away eventually, try running "sudo apt-get update"

**Comment by whoozle** [comment]
Unfortunately, it's likely Ubuntu problem, libfuse-dev listed wrong version number for its base library package. Usually these problems go away eventually, try running "sudo apt-get update"

sorry answered from wrong account first time.

**Comment by whoozle** [comment]
if you have older library installed, it may still work for you. Ignore it and try compiling AFTL
