### ISSUE TITLE
error: Get: invalid response code InvalidObjectHandle (0x2009)

### ISSUE THREAD

**Issue by pisto** [whoozle/android-file-transfer-linux#188]
I have a Mobiwire Kosumi, it appears to be a rebrand of some MikroTik MTK68xx device. No MTP clients appear to work, however this project seems to be the most active so I'll report it here.

From the cli, I get the following:
```
[pisto@pisto ~]$ aft-mtp-cli 
android file transfer for linux version continuous
MOBIWIRE Kosumi 1.0
extensions: microsoft.com: 1.0; android.com: 1.0;
MOBIWIRE Kosumi [100%]> ls
error: Get: invalid response code InvalidObjectHandle (0x2009)
MOBIWIRE Kosumi [100%]> 
```
dmesg is 
```
[ 1424.288056] usb 3-2: new high-speed USB device number 7 using xhci_hcd
[ 1424.415045] usb 3-2: New USB device found, idVendor=0e8d, idProduct=2008
[ 1424.415051] usb 3-2: New USB device strings: Mfr=2, Product=3, SerialNumber=4
[ 1424.415054] usb 3-2: Product: Kosumi
[ 1424.415056] usb 3-2: Manufacturer: MediaTek
[ 1424.415059] usb 3-2: SerialNumber: 0123456789ABCDEF
```
screen is unlocked. The cable is fine, I can charge and use `adb` with it.

**Comment by whoozle** [comment]
Why did you close it? I can help you investigate

**Comment by whoozle** [comment]
Try to run storage-list command and then select any storage apart from 'all'

**Comment by pisto** [comment]
I closed it because it was my mistake, I had mtp on in the debug settings
but not in the normal Android dialog, sorry.

**Comment by whoozle** [comment]
np, so I assume everything is fine for you? :D

**Comment by pisto** [comment]
Yes thank you.
