### ISSUE TITLE
Add indications to the "No MTP Device Found" message

### ISSUE THREAD

**Issue by Paviluf** [whoozle/android-file-transfer-linux#192]
Hello,

I'm on Fedora and the app wasn't working. I had the message "No MTP Device Found" when I opened the app (latest appimage). After some reading and some tinkering I unmonted the phone from Nautilus and the app worked. Maybe it could be good to add some indications to check the basics, to the "No MTP Device Found" message ?

Thanks !

**Comment by whoozle** [comment]
yes, sound like a good idea, and it's a common problem for many people.

**Comment by ipsod** [comment]
This was an issue for me.  I found this page when trying to solve it.

**Comment by whoozle** [comment]
it was there before, but got broken after I implemented multi-device support. I've started preliminary support of it, by removing Device::Find in flavour of external enumeration. Long story short, I've restored indication of "device busy" in fa7fe4d49616ba5fb8143ea9893476d160a502d0
 more stuff to follow:

The plan is:
1. provide list of process descriptors to upper layer in DeviceBusyException::Process [done]
3. remove FindFirst completely, add individual enumeration for every tool (cli/fuse), partially done for qt.
3. add api to kill them. 
4. Add buttons [Skip] [Terminate] to UI dialog, add CLI dialog in interactive mode, show pids to user in case of failure, just in case to deal with them manually

**Comment by whoozle** [comment]
please check 509bea3108d9c49aebef9c82d8831769ad32b222 or any later revision if you want

**Comment by Paviluf** [comment]
I don't use the app often but I wanted to report that the "Abort" button, when the device is mounted by an other program, work well. Thanks !

An other thing that can help other is that Android, at least on my Huawei P8 Lite 2017, set usb connection to "charge only" and don't ask for file transfert. I need to tap the "charge" notification and choose "file transfert" to make the app work.
