### ISSUE TITLE
no file transfer

### ISSUE THREAD

**Issue by cubetronic** [whoozle/android-file-transfer-linux#194]
No connection. Nothing works.
It used to work with the same devices and same software before updates/upgrades.

Device 1: Samsung ARMv7 Laptop (XE303C12)
Device 2: Samsung J3 Luna Pro (SM-S337TL)

```
[username@systemname ~]$ android-file-transfer 
upload worker started
device found, opening session...
10009 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying...
got unknown urb: 0xbefbf1a4
10007 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying...
got unknown urb: 0xbefbf1a4
10007 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying...
```

...then it spits out this GUI message:
MTP device does not respond

```
uname -a
Linux systemname 4.17.6-1-ARCH #1 SMP PREEMPT Fri Jul 13 00:41:20 UTC 2018 armv7l GNU/Linux
```
i'm running an LXDE desktop.

about 2 months ago i upgraded my system "pacman -Syu" to get a firefox upgrade to work, and it broke wifi, and broke my whole desktop environment, and rendered my laptop virtually useless. i finally fixed it by downgrading my dhcpcd package. (version 7 breaks my wifi, but version 6 is ok (that is still the case despite that bug being considered fixed and closed)). so now i'm getting everything to work again with dhcp 6, and so far everything is working except android-file-transfer.

### update:
tried compiling and running v3.4. i had to get the arch linux packages _cmake_, _qt4_, and _gcc_. it seemed to compile fine. still, no luck...
```
[username@systemname build]$ ./qt/android-file-transfer 
upload worker started
device found, opening session...
10010 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying...
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```
### update:
v3.2 works!!!

```
[username@systemname build]$ ./qt/android-file-transfer 
upload worker started
device found, opening session...
10009 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying...
device info "Samsung Electronics Co., Ltd."   "SM-S337TL"
device found, opening session...
device info "Samsung Electronics Co., Ltd."   "SM-S337TL"
switching to storage id  65537
session opened, starting
```

**Comment by whoozle** [comment]
Thanks a lot for your investigation! 
It's odd that the same error message is present on the last listing, but it did not crash.
I've seen this issue at some point, but it turned out to be faulty cable after all. 

Could you please try another cable first? 

But If you're still  suspecting that it's something introduced in the new code, you can try bisecting changes:
something like
```
git checkout master
git bisect start
git bisect bad
git bisect good v3.2
```
then follow its instructions.

**Comment by cubetronic** [comment]
I tried using a new high quality USB cable; no changes.

ArchLinuxARM repo:
community/android-file-transfer 3.5-1 [installed]
    Android MTP client with minimalistic UI

Version 3.5-1 doesn't work with either of my smartphones.

Version 3.2 works with my old Samsung Android 7 smartphone but not my new Motorola Android 7 smartphone.

Are there some dependencies that this program relies on that aren't being included when I get it from the repo? That's just a wild guess. Other than that, I'm using an ARMv7 laptop so I'm definitely not in the mainstream - so perhaps it has something to do with that. Sorry, no extra time to get into dissecting right now.

**Comment by whoozle** [comment]
Arm laptop! sounds awesome! Is it aarch64? 

No, no changes in deps really. If you're too busy to bisect, we can try to do some quick testing. 
There's a few new features were introduced between 3.2 and 3.5. I have a switch controlling usb interface claim.
My plan is to add off-switches for each of new feature, so you can just run just a few tests from command line and that's it. How does it sound? 

Could you run cli tool with -v first, and see where it freezes? 
I'll let you know when it's ready, but please add -v output here.

**Comment by cubetronic** [comment]
So I guess depending on Android File Transfer was probably the wrong way to go about things in the first place. I started with the advice on the main page about other MTP software, installed a bunch of things, and now I'm using Thunar (was using PCManFM) with automount which is great.

Not sure if I needed all these Arch packages, but these are what I got that made it work:
`gvfs-mtp autofs mtpfs thunar`

Unfortunately this does confirm that there is an issue with android-file-transfer, because I'm able to transfer files from both my phones now. I tested android-file-transfer after installing the above packages, but it still doesn't work.

**Comment by whoozle** [comment]
Sorry to hear that :)

It's known issue and I have no idea why it's happening, to me it looks like it's race condition in usbcore kernel module, but I'm not 100% sure. 
I've reproduced it using wireshark + usbmon module and it looks like urb is actually arriving, but kernel is not exiting poll() syscall, but it happens on next poll call.

**Comment by cubetronic** [comment]
just downloaded latest sources, compiled with cmake, compile looks fine, still getting same results...

```
$ ./qt/android-file-transfer -v
upload worker started
probing device...
probing device...
device found, opening session...
10006 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying...
got unknown urb: 0xbee4f1a4
10007 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying...
got unknown urb: 0xbee4f1a4
10007 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying...

```
maybe i'll bisect...

**Comment by cubetronic** [comment]
using my new Moto G5 Plus with a new cable...

here's the bisect:
```
$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[53230d606e44b7901e931a347b7f59ed3a963e2a] prepend mtp-ng library to MTP_LIBRARIES
```
and a show...
```
$ git show
commit 53230d606e44b7901e931a347b7f59ed3a963e2a (HEAD)
Author: Vladimir Menshakov <vladimir.menshakov@gmail.com>
Date:   Tue Apr 17 17:45:43 2018 +0100

    prepend mtp-ng library to MTP_LIBRARIES

diff --git a/CMakeLists.txt b/CMakeLists.txt
index 3abcbb1..eac5c91 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -146,11 +146,12 @@ if (BUILD_SHARED_LIB)
                target_link_libraries(mtp-ng ${LIBUSB_LIBRARIES})
        endif()
 
-       list(APPEND MTP_LIBRARIES mtp-ng)
+       list(INSERT MTP_LIBRARIES 0 mtp-ng)
        install(TARGETS mtp-ng LIBRARY DESTINATION "lib${LIB_SUFFIX}" ARCHIVE DESTINATION "lib${LIB_SUFFIX}")
 else (BUILD_SHARED_LIB)
        add_library(mtp-ng-static STATIC ${SOURCES})
        target_link_libraries(mtp-ng-static ${MTP_LIBRARIES})
+       list(INSERT MTP_LIBRARIES 0 mtp-ng-static)
        install(TARGETS mtp-ng-static LIBRARY DESTINATION "lib${LIB_SUFFIX}" ARCHIVE DESTINATION "lib${LIB_SUFFIX}")
 endif (BUILD_SHARED_LIB)
 ```
and a log...
```
$ git bisect log
git bisect start
# bad: [42c5421f5c05982cab9a24acb01f79277be14ebd] set cli tool to the first storage by default due to long-standing android mtp bugs
git bisect bad 42c5421f5c05982cab9a24acb01f79277be14ebd
# good: [39531602e3704e59ff74d162ecd1f0eba60dcfef] read version from readme if git failed :)
git bisect good 39531602e3704e59ff74d162ecd1f0eba60dcfef
# good: [90363ae622765dbf69011739d6ba78b82925512a] replaced hardcoded mpt-ng-static with ${MPT_LIBRARIES}, fixes #184
git bisect good 90363ae622765dbf69011739d6ba78b82925512a
# bad: [0bd35f526c9e6780844451411f7302e425988d19] use 2/3 of height for thumbnail
git bisect bad 0bd35f526c9e6780844451411f7302e425988d19
# bad: [88fc8e748d32111a918cb88e2a3e7b77bd63ad21] implemented abort/ignore dialog + opening retry
git bisect bad 88fc8e748d32111a918cb88e2a3e7b77bd63ad21
# bad: [81ca01af29171e28c9b6c13f3164ab8a747ea6dd] added Device::Open to probe devices individually
git bisect bad 81ca01af29171e28c9b6c13f3164ab8a747ea6dd
# bad: [561b28622540dcb8970d91a0d8b6609f19bb2747] renamed flatpak manifest to match distribution rules
git bisect bad 561b28622540dcb8970d91a0d8b6609f19bb2747
# bad: [c765c8ffaaf92ade9ede56bc760bfa8fb8a6dcf2] added minimal manifest for flatpak
git bisect bad c765c8ffaaf92ade9ede56bc760bfa8fb8a6dcf2
```

**Comment by whoozle** [comment]
bisect should automatically outputs first bad commit, e.g. 
```
xxxxxxx is the first bad commit
Author: xxxx
…
````
it looks like you have to do one more step :)

This commit looks absolutely harmless. To be sure, try reverting it, but I don't think it's the one, I'll take a look around this revision myself, but I can't reproduce it on any device I have.

**Comment by cubetronic** [comment]
bisect did not output the first bad commit. i know the docs say it will... but it didn't....
and it said 0 steps remaining.. so what do you mean by telling me i have one more step?

**Comment by whoozle** [comment]
Just test this revision and run ```git bisect bad / good``` as normal, it should output bad commit after that.

**Comment by cubetronic** [comment]
# good: [90363ae622765dbf69011739d6ba78b82925512a] replaced hardcoded mpt-ng-static with ${MPT_LIBRARIES}, fixes #184

is now bad.. i mean.. i tested it just now, just to check.. and it doesn't work..

**Comment by cubetronic** [comment]
i already reset the bisect a while ago

**Comment by cubetronic** [comment]
`$ uname -a
Linux host 4.19.0-1-ARCH #1 SMP PREEMPT Tue Oct 23 02:23:14 UTC 2018 armv7l GNU/Linux
`

**Comment by cubetronic** [comment]
ugh.. git bisect is absolutely idiotic.
`0 revisions left to test after this (roughly 0 steps)`
actually means
`1 revision left to test (this one) (roughly 1 step)`
nevermind the computer idea that counting starts at zero, this is idiotic.

so i bisected from 3.2 to 3.3 to save myself a bit of time and i got to here:
```
$ git bisect bad
1ddff3e5e75800772d1fd84611c443d750fd7168 is the first bad commit
commit 1ddff3e5e75800772d1fd84611c443d750fd7168
Author: Vladimir Menshakov <vladimir.menshakov@gmail.com>
Date:   Sun Jul 9 02:04:56 2017 +0100

    enabled zerocopy allocator if it's available

:040000 040000 ecac9ed8abfb5cf707d2867b830911bf2ecba1e2 bab423686373eca40b20212650292d9c42d0749f M	mtp
```

**Comment by whoozle** [comment]
That's something, thank you very much! I suspected it, because this was the biggest change since 3.2.

**Comment by cubetronic** [comment]
you're welcome!

first i tried just commenting out the first `if` for `_fd` and i tested that but it didn't help.. so i took a guess about how to also comment out the other `if` and then tested that and it worked... so that's all the pull request is...

i don't really understand what's going on there, i just figured i should try to make it look like it used to..

**Comment by whoozle** [comment]
please check 3475944e4d74e637f3676c4c571c482d398d7545 out, should be just fine! :)
I disabled it for now completely until further investigation.

**Comment by whoozle** [comment]
@cubetronic is the latest master working for you?

**Comment by maximumultraist** [comment]
I think it's somewhat excessive to disable zerocopy for all platforms based on an issue with ARMv7-A...

**Comment by whoozle** [comment]
Not really, I've seen it myself on my linux box (x86_64) quite often before some point when it disappeared, also I have numerous report of this. I even tried to debug it in kernel with no success. It looks like it's race condition in usb core. If you use epoll instead of sync REAP ioctl, it just does not wake you up, even though physically and logically USB URB was delivered to host. 

I'm going to reintroduce it as command-line switch + checkbox in UI in the next version .

**Comment by whoozle** [comment]
@cubetronic A bit of breakthrough happened recently. 
Could you please pull the latest changes and change `#if 1` to `#if 0` here, thus reenabling zero copy
```
#if 1
		mmap = false;
#endif
```
and then test it again, should solve all timeouts problem

**Comment by avolkov-astra** [comment]
aft-mtp-cli shows "error: timeout reaping usb urb"
I have found with git bisect that the bug was introduced by 2ff80c0b737af16f77219b552a31e23d38bf2bfa

**Comment by avolkov-astra** [comment]
Device::Reset() was forgotten to be called from the Device constructor.

**Comment by whoozle** [comment]
It's not really forgotten. The problem with reset, that it does not properly work for all hardware configurations. 
Freezes are very common if we turn it on. 

You can try passing `-R` to cli tool to see if it's reliably working for you.

**Comment by avolkov-astra** [comment]
Passing -R helps.
What about autoreset after catching "timeout reaping usb urb" error?

**Comment by avolkov-astra** [comment]
I still get the error with `aft-mtp-mount -R` after remount (mount, unmount, mount).
It can be fixed by changing the following code in mtp/ptp/Device.cpp
```
if (resetDevice && device) {
    device->Reset();
    device.reset();
    device = desc->TryOpen(ctx);
}
```
to
```
if (resetDevice && device) {
    device->Reset();
}
```
