### ISSUE TITLE
md5sum check

### ISSUE THREAD

**Issue by drizzle1** [whoozle/android-file-transfer-linux#195]
One of the files I copied was corrupted after the transfer.

Could a md5sum check option be included to check if the files were all copied correctly? 

I have used rsync a few times - which has a --checksum option, maybe this, or something similar can be implemented?

**Comment by tianon** [comment]
Not suggesting it's a fix to the issue, but as a workaround you should be able to use `aft-mtp-mount` to FUSE-mount the Android device and use `rsync` directly. :+1:

(The ability to FUSE-mount via `aft-mtp-mount` reliably is one of my favorite AFT features. :smile: :innocent:)

**Comment by whoozle** [comment]
Thanks @tianon ! This is my favourite feature too :+1:

**Comment by drizzle1** [comment]
Thanks Tianon, I will try this.

Dries
