### ISSUE TITLE
[CLI] Recursively download all files in a directory

### ISSUE THREAD

**Issue by marcelpaulo** [whoozle/android-file-transfer-linux#196]
I've just built AFTL from git master (509bea3108d9c49aebef9c82d8831769ad32b222) on Xubuntu 18.04.01, and I'm learning how to use it.

I'm interested in using the CLI in a bash script to recursively download all files under _Pictures_ and _Snapseed_, but haven't been able to. I got as far as:

1. Run the CLI interactively (`aft-mtp-cli`)
2. Change directory into _Pictures_ and _Snapseed_ (`cd Pictures`)
3. List all files in the directory (`ls`)
4. Get files/directories one by one (`get …`)

I was hoping to run something like this from a bash script:

```
aft-mtp-cli get 'Pictures/*'
aft-mtp-cli get 'Snapseed/*'
```

but each one gives me:

```
error: invalid argument count (0)
```

I managed to get a listing of all files/directories under _Pictures_, running:

```
aft-mtp-cli <<_EOT_
cd Pictures
ls
_EOT_
```

parsed the file/directory names, and then tried getting each one individually:

```
aft-mtp-cli Pictures/<file>
```

but I get the same error again:

```
error: invalid argument count (0)
```

So I'm clearly not getting the `get` command :-(

I'm really stuck, can't script this recursive download. I get the impression I'm overlooking something really basic. There are no issues open or closed regarding this, so I'm supposing everyone knows how to do it, but me :-(

By the way, really nice touch the autocompletion in the interactive CLI session!

**Comment by whoozle** [comment]
added FAQ entry in a4728bf9e4adfc29a4f8e35f252a9e531cf87bc6

**Comment by marcelpaulo** [comment]
> Pass all commands as single strings

Worked like a charm!

> There's -b switch, basically forcing cli tool to read commands from input and process them one by one

Worked like a charm too!

> added FAQ entry in a4728bf

Excelent idea. Next person who hits the same doubt won't open an issue.

Thanks for all the info!

**Comment by whoozle** [comment]
np!
