### ISSUE TITLE
No icons under macOS

### ISSUE THREAD

**Issue by yurikoles** [whoozle/android-file-transfer-linux#204]
![10 39 56](https://user-images.githubusercontent.com/922873/47344129-6dd40600-d6b0-11e8-86b4-01c00e46a23c.png)
But I have icons installed by `kde-mac/kde/kf5-breeze-icons`.

```
$ ls "$HOME/Library/Application Support"/icons
Adwaita  breeze  breeze-dark  hicolor
```

**Comment by d1vanov** [comment]
As far as I can see, the icon themes are only ever mentioned in `mainwindow.ui` file. On Linux distros that's enough because the "built-in" icon themes actually exist but on Windows and macOS they don't exist. So if the app wishes to use some icon theme on those platforms, it should package one (or more than one) within itself (using [qrc](https://doc.qt.io/qt-5/resources.html), for example) and/or provide a way for the user to specify where should the icons be searched for using [QIcon::setThemeSearchPaths](https://doc.qt.io/qt-5/qicon.html#setThemeSearchPaths).

**Comment by yurikoles** [comment]
Please note: there is a [pending PR](https://codereview.qt-project.org/#/c/238640/) in Qt, to allow custom paths for resources under macOS:

**Comment by joergister** [comment]
I don't see them either. 
I'm on Fedora KDE and I'm using the appimage.
Doesn't matter if I use the dark theme (breeze) or the standart breeze theme.
In both cases I don't see them.

**Comment by joergister** [comment]
With Prerelease of https://github.com/whoozle/android-file-transfer-linux/commit/1448da31b570677c0dbcf2e2daf2c254055d44fd this is still the case. 
Starting the appimage results in:

```
./Android_File_Transfer-1448da3-x86_64.AppImage 
upload worker started
probing device...
probing device...
probing device...
probing device...
device found, opening session...
device info "*********"   "*********"
switching to storage id  *******
session opened, starting

```

and a UI without icons, just like this :


![screenshot_20190207_202214](https://user-images.githubusercontent.com/24881413/52437380-0fc01700-2b17-11e9-8810-75fab0f4755d.png)

**Comment by Jeinzi** [comment]
Update for those Arch+i3 users here:
`qDebug() << QIcon::themeName()` told me that the application tried to load the hicolor icon theme, which does not contain any generic icons at all on my system.
I solved the problem by following the [arch wiki](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications#Using_a_GTK_icon_theme_in_Qt_apps) and
- Using dconf-editor to set `org > gnome > desktop > interface > icon-theme`
- `echo export DESKTOP_SESSION=gnome >> ~/.xinitrc`

so Qt applications use an icon theme of my choosing.

**Comment by whoozle** [comment]
I just removed all themes alltogether and used old QStyle method in 291f4d582508f53528a2dc0f746755d1ac0b4d70

Should be fine now

**Comment by joergister** [comment]
I tested it and can confirm this is right. 
problem solved.
THX a lot.

**Comment by whoozle** [comment]
@joergister default icons are ugly as heck :sob:

**Comment by joergister** [comment]
I have to admit, they could be more pretty ;) but having icons at all ist better than not having icons.
