### ISSUE TITLE
[FR]FUSE support for macOS?

### ISSUE THREAD

**Issue by yurikoles** [whoozle/android-file-transfer-linux#209]
We have a FUSE for mac via [osxfuse](https://osxfuse.github.io/), please add support for it.

**Comment by whoozle** [comment]
Unfortunately I don't have any Mac hardware around.

**Comment by whoozle** [comment]
Duplicate of #114 
Someone told that he was able to build and run it. Could you investigate please?

**Comment by whoozle** [comment]
Argh, it was just macosx build, no fuse.

**Comment by yurikoles** [comment]
@whoozle please reopen.

**Comment by whoozle** [comment]
Why? #114 is still open, it's about the same thing.
