### ISSUE TITLE
Certain characters in file names aren't recognized

### ISSUE THREAD

**Issue by epahlberg** [whoozle/android-file-transfer-linux#211]
I have several characters, with non english letters (ö,ä,ü,õ) and they aren't recognized, when trying to upload files. Example: I have file named "HU - Läbi Öö.mp3", but application reads it as "HU - Lbi.mp3", therefore not finding file.

**Comment by epahlberg** [comment]
Because I had problems with my locale settings, once I fixed them then application read file names correctly, sorry for false issue :)

**Comment by whoozle** [comment]
Great, I hope AFTL worked for you!

**Comment by epahlberg** [comment]
Yes, so far it has been working, thanks!
