### ISSUE TITLE
Support in CLI for "Move" operation.

### ISSUE THREAD

**Issue by JeremyLaurenson** [whoozle/android-file-transfer-linux#212]
I have a stubborn device that works only I use "move" on a PC:

Does this make sense?
https://www.youtube.com/watch?v=8Mfh01l3z4c&feature=youtu.be

**Comment by whoozle** [comment]
I'm really sorry that it took so long to answer. I moved before NY, and it was pretty much intense :D

This is pretty weird, and maybe it has something to do with object type detection. You can always reach me by email if I missed your issue.

**Comment by whoozle** [comment]
what extension your playlist file have? is it `.m3u` or `.m3u8`?

**Comment by JeremyLaurenson** [comment]
Both :-)

This is not desperate.
