### ISSUE TITLE
Only newly created files have write permission

### ISSUE THREAD

**Issue by leo60228** [whoozle/android-file-transfer-linux#215]
If I create a file, it is writable, but existing ones are read-only. I cannot chmod them to be writable, but if I write bypassing permissions (ex. through `:w!` in vim), the write is successful.

**Comment by whoozle** [comment]
are you mounting your phone with aft-mtp-mount?

**Comment by leo60228** [comment]
No. I'm mounting a Nintendo Switch using nxmtp, which is closed source. I've also opened an issue there.

**Comment by whoozle** [comment]
That's a bit confusing, why do you create issue here then?

**Comment by leo60228** [comment]
Other MTP implementations such as Windows 10 and kio-extras don't have this problem.

**Comment by yurikoles** [comment]
@leo60228
Do you have any evidence that they are use code from this repo, e.g. steal and close source code?

**Comment by leo60228** [comment]
No.

**Comment by whoozle** [comment]
@leo60228 are you willing/able to help me by patching code locally and submitting PR later? Probably this is faster than me guessign where the problem is. I'll support you with code location and stuff.
Thanks

**Comment by leo60228** [comment]
Sure. It's C#, right?

**Comment by leo60228** [comment]
"are you mounting your phone with aft-mtp-mount?" I just realized what you meant. I am using aft-mtp-mount, but the device is a Nintendo Switch running nxmtp.

**Comment by leo60228** [comment]
This is why I shouldn't comment on issues at 7AM. I meant C++.

**Comment by whoozle** [comment]
No, It's C++,  what platform do you have? Linux? 
Are you mounting without sudo/not using root account? Can you try passing ```-o allow_other``` to 
aft-mtp-mount

Take a look into, https://github.com/whoozle/android-file-transfer-linux/blob/master/fuse/FuseEntry.h
0755 means rwxr-x-r-x, but 0444 means r--r--r--, I have no idea why I did this lol. 
```
   static constexpr unsigned 		FileMode 		= S_IFREG | 0444;
   static constexpr unsigned 		DirectoryMode	= S_IFDIR | 0755;
```

Can you fix FileMode to 0600 and see if it helps?
```
   static constexpr unsigned 		FileMode 		= S_IFREG | 0600;
   static constexpr unsigned 		DirectoryMode	= S_IFDIR | 0700;

```

**Comment by leo60228** [comment]
I'm mounting without sudo, but the files are owned by root. I'll try those when I get home in around 8-9 hours (5PM EST).

**Comment by whoozle** [comment]
Ignore it, 
I found that you can edit files using github editor right from the browser :)
should be fixed in 0716cfb2cd0dba8b5fdddd7f257c8db049fa9107

Please pull, recompile and test it.

**Comment by leo60228** [comment]
Sorry for taking so long, compiling it now.

**Comment by leo60228** [comment]
That worked! Thank you so much!

**Comment by whoozle** [comment]
Thanks for your feedback and testing! Hopefully everything will work fine for you
