### ISSUE TITLE
got unknown urb: 0xbff22b2c

### ISSUE THREAD

**Issue by FrancescoS001** [whoozle/android-file-transfer-linux#217]
Hi all, I can't mount my Lumia 830 on Linux Xubuntu 18.04.02

If I try to run ./qt/android-file-transfer on terminal I got this:
"upload worker started 
probing device...
device found, opening session... 
10009 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying... 
10007 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying... 
**got unknown urb: 0xbff22b2c**
10009 ms since the last poll call
timed out getting device info:  "timeout reaping usb urb" , retrying... "

What Can I do to solve this? Normal MTP does not work 

![Istantanea_2019-05-04_13-08-11](https://user-images.githubusercontent.com/50264352/57178249-cbba8500-6e6d-11e9-8508-5a2d58af1efb.png)

**Comment by whoozle** [comment]
please check the latest master, I've added some reset routines today

**Comment by FrancescoS001** [comment]
> please check the latest master, I've added some reset routines today

Ok thanks, I'll try it

**Comment by whoozle** [comment]
@FrancescoS001 any luck yet? :)

**Comment by FrancescoS001** [comment]
> @FrancescoS001 any luck yet? :)

It works! :D thanks

**Comment by whoozle** [comment]
awesome! this is long-term issue I couldn't not tackle :)
