### ISSUE TITLE
Multiple items in file list

### ISSUE THREAD

**Issue by guckstift** [whoozle/android-file-transfer-linux#222]
After a downloading procedure the file list contains all directory entries multiple times.
![multiple](https://user-images.githubusercontent.com/16594755/58158528-ecab1480-7c7a-11e9-8b8a-eccac661daac.png)

**Comment by whoozle** [comment]
What if you press refresh after that?

**Comment by guckstift** [comment]
After refreshing it stays the same.
I built from the latest release 3.8 source on linux mint 19 64bit

**Comment by whoozle** [comment]
Can you try running cli tool?

**Comment by whoozle** [comment]
Run aft-mtp-cli in console, then try help, list-storage, change storage and then list files.

**Comment by guckstift** [comment]
In the cli everything seems to work fine. I can change storage back and forth , list storage, list files, download some directory, list files again -> the file list seems fine without duplicates.

**Comment by whoozle** [comment]
Nice! I was worried that UI trashed your card :)

**Comment by guckstift** [comment]
No, thats cool :D actually after restarting the GUI the directory list is correct again. Maybe some bug in the GUI? list view nodes added to many times?

**Comment by whoozle** [comment]
very similar with #60

**Comment by akostadinov** [comment]
I see the same issue with Galaxy S9. Actually initially it worked well but at some point started to show duplicates.



```
$ android-file-transfer 
upload worker started 
probing device...
probing device...
probing device...
probing device...
probing device...
probing device...
device found, opening session... 
device info "Samsung Electronics Co., Ltd."   "SM-G960F" 
switching to storage id  65537 
session opened, starting 
switching to storage id  131074 
...
```

![aft](https://user-images.githubusercontent.com/1408661/60097643-6fccf800-975c-11e9-9b90-8cbbd955c48c.png)

**Comment by whoozle** [comment]
Can anyone check with the latest 4.0 release please?

**Comment by akostadinov** [comment]
I can't reproduce right now with 3.9 and Galaxy S9 latest update (Android 10). So probably I can't help with this issue anymore.
