### ISSUE TITLE
v3.8: connection keeps resetting; no success with aft-mtp-mount or aft-mtp-cli

### ISSUE THREAD

**Issue by piater** [whoozle/android-file-transfer-linux#223]
Just upgraded to v3.8 on my up-to-date Arch Linux system. `aft-mtp-mount` does not complain and `fuse` appears to mount, but the phone keeps flashing up the USB connection confirmation dialog, and the mounted directory appears empty. Using `aft-mtp-cli` to `put` something results in the message:

> your device may be locked or does not have any storage available

I downgraded to v3.7, and everything works fine as before.
I have cloned the repo, compiled and reproduced this with my fresh build. Feel free to have me test patches.

**Comment by whoozle** [comment]
I'll make reset optional, because it seems to be disruptive for many people (and FreeBSD affected as well). I haven't seen it on any usb device I have, maybe it's something to do with USB hub behaviour or something. 

Please pull and test if you can

**Comment by piater** [comment]
Works like a charm, thanks!
