### ISSUE TITLE
Mounting read only still allows creating directories

### ISSUE THREAD

**Issue by akostadinov** [whoozle/android-file-transfer-linux#225]
Hi, I noticed mounting my Galaxy S9 is read-only as stated in `README.md`. Still I was able to create a directory on `CARD`.

Not a huge issue but it is strange. Deleting that directory caused app to crash.

**Comment by whoozle** [comment]
Can you test with the latest master please? What's your operating system?

**Comment by akostadinov** [comment]
If latest works for you, feel free to close. On Fedora 32 right now. Not sure how to install latest version and for such small bug, not worth it.

**Comment by whoozle** [comment]
Ah, I got it now. Maybe I should add a clearer message for that. If your phone is missing partial write extension, you can't write into individual files, but it's allowing you to do anything else, e.g. create directories, rename local files, delete stuff. Newer Samsung phones have this extension. 
9670af18cc03b50ac0a455c9fd74da1706b7c67b
