### ISSUE TITLE
MacOS Sandbox

### ISSUE THREAD

**Issue by JeremyLaurenson** [whoozle/android-file-transfer-linux#229]
Hey V

I need to be able to run the cli app inside the MacOS sandbox. I can launch it from my code in order to inherit my permissions, BUT MacOS requires that it be "sandboxed" as Apple ratchets up their security strangleholds.

An Info.plist is what defines different properties about the app and is in the app bundle. However, a command line binary doesn’t have a bundle with an Info.plist in it.

I know you can tell GCC to inject a info.plist into a binary during compilation by including a CC variable to add a gcc flag to include the sandbox permissions plist file like this:

./configure CC=”gcc -sectcreate,__TEXT,__info_plist,/path/to/avrdude-info.plist”

I have no idea how I would do a similar operation using the aft-mtp-cli project.

Any suggestions?

**Comment by whoozle** [comment]
@d1vanov hi, can you take a look into that if you have some time? or at least recommend me where to look. Still don't have any mac os x device lol :)

**Comment by d1vanov** [comment]
> @d1vanov hi, can you take a look into that if you have some time? or at least recommend me where to look. Still don't have any mac os x device lol :)

Hi there, unfortunately I can't help here, I don't have any Mac device of my own and I lost access to the one I used about a year ago.

**Comment by yurikoles** [comment]
Привет @d1vanov!
I'm volunteering to provide SSH access if it helps :)

**Comment by JeremyLaurenson** [comment]
I managed to get this going in a roundabout way:
use 
`cmake -G Xcode ..

to make the project for Apple's Xcode IDE. Then open the project and make sure to turn code signing on for the target, including adding the entitlements you need by creating an .entitlements file:

![Screen Shot 2019-11-18 at 12 18 11 PM](https://user-images.githubusercontent.com/942556/69104372-f9e06a80-0a35-11ea-8bcf-ac4001ffe35a.png)
![Screen Shot 2019-11-18 at 12 17 59 PM](https://user-images.githubusercontent.com/942556/69104374-fcdb5b00-0a35-11ea-9f66-67d9542a4c8a.png)

This is essentially porting into Xcode in order to use their code sign/sandbox entitlements capabilities.

**Comment by JeremyLaurenson** [comment]
I am going to close this for the moment. I'm not sure if you want this documented as a method should someone need the same.

**Comment by whoozle** [comment]
it's definitely useful addition, this should be doable from normal ninja/make too, I believe
