### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by clancyj4** [whoozle/android-file-transfer-linux#234]
During the build process on a git cloned copy, the cmake works OK, but the make results in the following error:

/work/android-file-transfer-linux/mtp/ptp/Response.h:40:12: fatal error: mtp/ptp/ResponseType.values.h: No such file or directory
 #  include <mtp/ptp/ResponseType.values.h>

I've checked and there is no ResponseType.values.h anywhere in the source.

**Comment by whoozle** [comment]
I'm really sorry about that, it looks like I forgot to add file, I'll fix it tonight

There's quite a lot of changes recently, you can either checkout the latest release, or alternatively the latest good revision
I reckon it's ecd6f918c0bfadd54905014cbf30efa0963ac4b7

**Comment by whoozle** [comment]
There's a lot of things going on: 
I'm aiming to fully support Zune/Zune HD, including mtpz (working now), there's new python binding based on pybind11, and a lot of overall code improvements.

**Comment by clancyj4** [comment]
Thanks.  I'll check it out on GitHub tomorrow.

**Comment by clancyj4** [comment]
Sorted.  Thank you.
