### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by d3im** [whoozle/android-file-transfer-linux#239]
I'd like to make czech translation. Is it sufficient to make file from e.g. italian translation?

**Comment by d3im** [comment]
I made translation, then:
```
lrelease android-file-transfer-linux_cs_CZ.ts
cp android-file-transfer-linux_cs_CZ.qm /usr/share/qt5/translations/
```
but still no translation

**Comment by whoozle** [comment]
I think you have to add `.qm` file to `android-file-transfer.qrc` as it's done for russian. I just checked Russian and it's working. I'm not sure why Italian isn't on the list, probably it has to be :)

**Comment by d3im** [comment]
OK finally I was able to incorporate translation but it seems it's outdated (created from italian file) ;-)

**Comment by d3im** [comment]
I mean is there any complete translation file? I'm willing to send (and care of) czech translation of Your tool.

**Comment by whoozle** [comment]
Sorry, I should've provided more detailed answer, I thought you're familiar with ts files workflow

The only command you need is something like below
`lupdate qt -ts qt/translations/android-file-transfer-linux_cz.ts`
It's updating your translation file according to the current sources and using heuristics to detect simple punctuation fixes, etc
then, you open this ts file with Qt Linguist and provide localised strings:
`linguist qt/translations/android-file-transfer-linux_cz.ts`

I hope this helps, don't hesitate to ask help here. :)

Thanks

**Comment by whoozle** [comment]
fixed in
https://github.com/whoozle/android-file-transfer-linux/pull/241
