### ISSUE TITLE
Provide icon and desktop file

### ISSUE THREAD

**Issue by lucidfox** [whoozle/android-file-transfer-linux#24]
The application should have an icon and a .desktop file to properly integrate with Linux desktops.

Here is an example .desktop file (to be placed in /usr/share/applications/android-file-transfer.desktop)

```desktop
[Desktop Entry]
Name=Android File Transfer
Comment=Transfer files to and from MTP devices
Exec=android-file-transfer
Icon=android-file-transfer
StartupNotify=false
Terminal=false
Type=Application
Categories=Utility;FileTools;Filesystem;Qt;
```

**Comment by whoozle** [comment]
Added in 52f8de5ab71f8107794ff2513cb4650d507d30f1
