### ISSUE TITLE
Question: Transfer Rate MBps or Mbps?

### ISSUE THREAD

**Issue by rajeshisnepali** [whoozle/android-file-transfer-linux#242]
![android_file_transfer_transfer_rate](https://user-images.githubusercontent.com/23610013/83089847-13363380-a0b7-11ea-8fc5-84ce681a85a1.png)

I have a question. Was that MBps or Mbps? 

Before the app, I use to use FTP for transferring larger files. I was getting 25-27 MBps via nautilus (< 1GB files). 

Please let me know.

**Comment by whoozle** [comment]
It's megabytes with base of 1000.I have a feeling that it should be fixed, because it's misleading and gives wrong impression of speed

Please find piece of code which updates progress dialogue:
```
	static constexpr double Kb = 1000;
	static constexpr double Mb = 1000 * Kb; //haha
	static constexpr double Gb = 1000 * Mb;
	if (speed < 2 * Mb)
		ui->speedLabel->setText(tr("Speed: %1 Kb/s").arg(speed / Kb, 0, 'f', 1));
	else if (speed < 2 * Gb)
		ui->speedLabel->setText(tr("Speed: %1 Mb/s").arg(speed / Mb, 0, 'f', 1));
	else
		ui->speedLabel->setText(tr("Speed: %1 Gb/s").arg(speed / Gb, 0, 'f', 1));
```

**Comment by rajeshisnepali** [comment]
I have installed it via the Ubuntu Store. So I don't think I've much option to configure. Better is to wait until the issue is fixed. 

Please fix it soon. Thanks.
