### ISSUE TITLE
Fix USB async events for composite devices

### ISSUE THREAD

**Issue by arturmadrzak** [whoozle/android-file-transfer-linux#248]
Refer to [libmtp PR](https://github.com/libmtp/libmtp/pull/63):
Async events (cancel and status) doesn't work for composite devices, when
MTP interface is not located as the first one in the descriptors. Control transfers,
by default are addressed to interface 0 but should be addressed to
actual interface. For this purpose wIndex field should contain
address of target interface.

The error line is located here:
https://github.com/whoozle/android-file-transfer-linux/blob/24089ee7186a4223df64e81033e1ab07542b51a2/mtp/ptp/PipePacketer.cpp#L252

and code should look like:
```
_pipe->GetDevice()->WriteControl(
			(u8)(usb::RequestType::HostToDevice | usb::RequestType::Class | usb::RequestType::Interface),
			0x64,
			0, _interface_number_, req.Data, timeout);
```

**Comment by whoozle** [comment]
Thanks for reporting this, feel free to reopen if it's not working!
