### ISSUE TITLE
need support to mount more than two devices

### ISSUE THREAD

**Issue by oucaijun** [whoozle/android-file-transfer-linux#253]
Hello,

I used `aft-mtp-mount ` to mount two android mobiles and `gio GVolumeMonitor` to monitor the mount-event. The  `gio GVolumeMonitor` can only monitor the mount-event of the first mobile.

(The reason for use `gio and aft-mtp-mount ` is  `aft-mtp-mount` can read/write the android mobile more fast and `gio GVolumeMonitor` make it easy to monitor the mobile and get mobile device info, seems they constitute a complementary relationship.)

```

step1: mount device 1

$./build/fuse/aft-mtp-mount ~/my-device-2


step2: mount device 2

$./build/fuse/aft-mtp-mount ~/my-device

step3: use gio to enum the mount.

$ gio mount -li | grep my
Mount(1): my-device -> file:///home/ocean/my-device
  default_location=file:///home/ocean/my-device
Mount(5): my-device -> file:///home/ocean/my-device
  default_location=file:///home/ocean/my-device


step4:  show mounts

$ cat /proc/mounts | grep my-device
aft-mtp-mount /home/ocean/my-device fuse.aft-mtp-mount rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
aft-mtp-mount /home/ocean/my-device-2 fuse.aft-mtp-mount rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0


```

I found the reason is the device path `aft-mtp-mount` is the same for both and thus the second mount is ignored.

I am wondering how to automatically generate mount paths and device paths with `aft-mtp-mount `,  can we make `aft-mtp-mount` to run with an automatic rule to do this job?

I will REALLY appreciate your reply. Thank you!

**Comment by whoozle** [comment]
The third field is called "subtype", and it's the application name by default, hence fuse.aft-mtp-mount.

Any ideas what to put in there? There's a few options I can see, but all of them have its own advantages/disadvantages
1. USB bus/port id (not the usb id, but device index in bus/hub). This is unique, but may change with OS upgrade or plugging device in different port.
2. Device serial number? Unique, could be unsupported by device.
3. Allow you to pass subtype as an option similar to `fuse.mount -subtype=whatever-you-want`?

**Comment by oucaijun** [comment]
In order to let `gvfs` it to monitor more than one mobiles, the first field have to be defferent.

I did experiment as follow, then the GIO can monitor the mobiles.

The basic requirement is that a mobile can be uniquely identified before the computer is turned off.  Friendly device name and memory function are bonus items, I think.

The device id like `HUAWEI_VOG-AL00_MQS0220407000985` can be a choice. And I think it's better to make a rule than to let users play freely.


```
step1: mount device 1

$./build/fuse/aft-mtp-mount  ~/my-device


step2: mount device 2

$./build/fuse/aft-mtp-mount-2  ~/my-device-2

step3: use gio to enum the mount.

$ gio mount -li | grep my
Mount(1): my-device -> file:///home/ocean/my-device
  default_location=file:///home/ocean/my-device
Mount(5): my-device -> file:///home/ocean/my-device-2
  default_location=file:///home/ocean/my-device-2

step4:  show mounts

$ cat /proc/mounts | grep my-device
aft-mtp-mount /home/ocean/my-device fuse.aft-mtp-mount rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
aft-mtp-mount-2 /home/ocean/my-device-2 fuse.aft-mtp-mount rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0

```

**Comment by whoozle** [comment]
starting from fdae9f1ed290a9ed02c9afe0e2c5d6260ccb04e0 you don't even have to provide mountpoint, it will be generated automatically using Vendor-Model-Serial pattern, also it's possible to filter devices using `-d`, e.g. `aft-fuse-mount -d nexus` will mount first nexus device at `LGE-Nexus-5X-1234556`. `-d` also allows to specify USB vendor/product id in hex, e.g. `-d 0055:1123`

**Comment by whoozle** [comment]
Feel free to reopen/create new issue if you miss anything
