### ISSUE TITLE
Slow file moving and deletion

### ISSUE THREAD

**Issue by mb720** [whoozle/android-file-transfer-linux#272]
Hi!

I assume this is a limitation of MTP, but I was wondering why deleting or moving files is rather slow.

I have the internal storage of a Samsung Galaxy J5 mounted using `aft-mtp-mount`. Being used to the behavior of ext4, NTFS, and FAT, I was expecting that deleting or moving a file is fast, since only the values of an inode or a directory entry have to be changed.

But it seems that when moving files from one directory of the phone to another directory (still on the phone), all the bytes of the files have to be moved. Similar when deleting files: from the time it takes, it looks as if the bytes of the file are overwritten.

I'm curious how moving and deleting are implemented in MTP since the operation seem to take time proportional to the size of the file.

**Comment by whoozle** [comment]
MTP spec says MoveObject is optional and I haven't seen it in real device even once. 

There's some limited support for renaming within one directory (should be fast using fuse).  Normally all those operations are happening in database, and also RemoveObject is recursive, potentially it's very slow.

**Comment by whoozle** [comment]
Rephrasing a bit it means execution time does not really depend on file system performance, but more on internal media database performance. In android it's normally sqlite, and it's not very good with large number of rows inside.

**Comment by whoozle** [comment]
Investigated as a part of #56
