### ISSUE TITLE
gplv3?

### ISSUE THREAD

**Issue by zabbal** [whoozle/android-file-transfer-linux#28]
Is there any particular reason why older version was chosen?

**Comment by whoozle** [comment]
The GPLv3 contains an explicit patent license, according to which people who license a program under the GPL license both copyrights as well as patents to the extent that this is necessary to use the code licensed by them.  A comprehensive patent license is not thereby granted.  Furthermore, the new patent clause attempts to protect the user from the consequences of agreements between patent owners and licensees of the GPL that only benefit some of the licensees (corresponding to the Microsoft/Novell deal).  The licensees are required to ensure that every user enjoys such advantages (patent license or release from claims), or that no one can profit from them.

Well, basically I don't think that gplv3 is compatible with existing microsoft/google patents

**Comment by zabbal** [comment]
Kind-of true but it only matters if you're microsoft/google. I really doubt that you're holder of any software patents under US jurisdiction hence you're free to use GPLv3 for your code without any issues.

**Comment by whoozle** [comment]
So, what's wrong with gplv3?

**Comment by zabbal** [comment]
For you and me - nothing. For huge corporation with large patent pool - GPLv3 might prevent it from engaging in "patent war" lawsuit.

**Comment by whoozle** [comment]
Is it good then? :)

**Comment by whoozle** [comment]
I changed license to gplv3 like few days ago or something. Starting from the commit 0c39665a2f6cb1e9c1e582d5e53160f2b785dd8a

**Comment by zabbal** [comment]
Definitely. Consider it as a GPLv2 + bugfixes.
Unless you're lawyer who's job is to suck on other people's creativity :)

**Comment by whoozle** [comment]
Well, yes, I've been advised to do this multiple times, on reddit and other places. Thanks for reporting. Sorry for this misunderstanding.
