### ISSUE TITLE
buntu 21.10/snap/v4.2.7 - Could not open network socket

### ISSUE THREAD

**Issue by NicolasGoeddel** [whoozle/android-file-transfer-linux#294]
Hi,
I just installed the software via
```
$ sudo snap install android-file-transfer-linux
android-file-transfer-linux 4.2+git aus Vladimir Menshakov installiert
$ android-file-transfer-linux.a<tab>
android-file-transfer-linux.aft-mtp-cli            android-file-transfer-linux.aft-mtp-mount          android-file-transfer-linux.android-file-transfer
```
Unfortunately I get these errors:
```
$ android-file-transfer-linux.android-file-transfer 
Qt: Session management error: Could not open network socket
upload worker started
current text color value:  0 , guessed theme:  "light"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
scan
terminate called after throwing an instance of 'mtp::posix::Exception'
  what():  opendir: Permission denied
Abgebrochen
```
This is showing the help at least:
```
$ android-file-transfer-linux.aft-mtp-cli -h
usage:
-h	--help		show this help
-v	--verbose	show debug output
-i	--interactive	force interactive mode
-b	--batch		batch command processing
-e	--events	allow event processing
-f	--input-file	use file to read input commands
-C	--no-claim	no usb interface claim
-R	--reset-device	reset usb device before connecting
-d	--device-name	use device name (could be partial name, e.g. model or manufacturer)
-l	--device-list	list devices
-V	--version	show version information
```
But interactive mode fails too:
```
$ android-file-transfer-linux.aft-mtp-cli -i
terminate called after throwing an instance of 'mtp::posix::Exception'
  what():  opendir: Permission denied
Abgebrochen
```
I am not sure how to use the other options. I did not try it with `sudo` because I think it should work without too, am I right?

Here is the `snap info android-file-transfer-linux`:
```
name:      android-file-transfer-linux
summary:   Simple and reliable MTP client
publisher: Vladimir Menshakov
store-url: https://snapcraft.io/android-file-transfer-linux
contact:   vladimir.menshakov@gmail.com
license:   unset
description: |
  Simple UI + Fuse wrapper + cli tool for exploring, downloading, uploading
  data from/to your MTP device. Supports Zune/Nintendo Switch.
commands:
  - android-file-transfer-linux.aft-mtp-cli
  - android-file-transfer-linux.aft-mtp-mount
  - android-file-transfer-linux.android-file-transfer
snap-id:      4j2bVoXp8juuKI7EbOARnRX389hps9t1
tracking:     latest/stable
refresh-date: heute um 21:59 CET
channels:
  latest/stable:    4.2+git 2021-01-12 (199) 110MB -
  latest/candidate: ↑                              
  latest/beta:      ↑                              
  latest/edge:      4.2+git 2022-01-11 (294) 110MB -
installed:          4.2+git            (199) 110MB -
```
And `lsb_release -a`:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```

**Comment by kr5ture** [comment]
Same issue here.

**Comment by philb61** [comment]
Same problem here on Ubuntu 21.10.

I ended up compiling from source, and that works fine.  FYI, if you want the python bindings, you'll also need to:

`pip install "pybind11[global]"`

(not sure I'll ever use those, but they're at least built in now.)

**Comment by whoozle** [comment]
What's your home directory, is it inside `/home` or somewhere else?

**Comment by NicolasGoeddel** [comment]
It is `/home/nicolas`. But it is mounted on a different drive and encrypted with LUKS if that makes any difference but I hope not.

**Comment by whoozle** [comment]
There's known problem with home directories which are not in `/home` or symlinked from `/home` to somewhere else. Do you have symlink or it's just mounted at `/home/nicolas`?

**Comment by NicolasGoeddel** [comment]
`/home` ist mounted on `/dev/mapper/luks-home`. That's all. The subdirectories inside `/home` are normal directories, no symlinks.

**Comment by whoozle** [comment]
great, then probably the next build will fix it - it seems I have to add `personal-files` to plug list. Maybe even `system-files`.

**Comment by NicolasGoeddel** [comment]
Sounds promising. Looking forward to the next release.

**Comment by whoozle** [comment]
not release, I just triggered next snap build, it would be great that you can checked (unfortunately I don't have ubuntu machine anymore, maybe it's worth installing it in virtual machine, but I can't promise it happens soon :( )

**Comment by whoozle** [comment]
unfortunately they are not allowing using personal files without bureaucracy bullshite and my request has been failed. This means, no snaps anymore, as they will not work.

**Comment by whoozle** [comment]
I'm pulling snaps off the snapstore, I'm really sorry about that

**Comment by whoozle** [comment]
5928ffb635d7ad1a2ffad51fb4afe9fce3bb69e7
