### ISSUE TITLE
[WP] Can't delete a file

### ISSUE THREAD

**Issue by trufanov-nok** [whoozle/android-file-transfer-linux#30]
I'm getting ``Get: Invalid response code InvalidParameter (0x201d)`` any time I'm trying to delete a file on WP device. Console:
```
./qt/android-file-transfer 
upload worker started
device info "NOKIA"   "909"
device found, opening session...
session opened, starting
remove rows  4   1
```
File isn't removed neither from device disk nor from GUI.
wireshark trace: http://1drv.ms/1d8dswD
(Only file deletion attempt is captured)

**Comment by whoozle** [comment]
Session.cpp:299
Please try replacing this line:
```Send(OperationRequest(OperationCode::DeleteObject, transaction, objectId));```
with 
```Send(OperationRequest(OperationCode::DeleteObject, transaction, objectId, 0));```
And see if it helps.

**Comment by trufanov-nok** [comment]
Yes, it fixes the problem.

**Comment by whoozle** [comment]
Microsoft engineers can't read their own standards then.

**Comment by trufanov-nok** [comment]
Have no doubts in that
