### ISSUE TITLE
Gentoo ebuild update request

### ISSUE THREAD

**Issue by scottfurry** [whoozle/android-file-transfer-linux#308]
From message posted to gentoo-dev (see [message here](https://archives.gentoo.org/gentoo-dev/message/13aa993921f19b6b095297721ffb0d0b)), python-3.10 is to become default in June.

Current ebuild enables only python-3.8 and python-3.9.

Unknown if project maintains ebuild for gentoo tree.

**Comment by whoozle** [comment]
no, I don't maintain ebuilds for gentoo, although I can test (I'm using gentoo myself), is there anything I can help you with?
