### ISSUE TITLE
FUSE does not write files to samsung devices

### ISSUE THREAD

**Issue by repsac-by** [whoozle/android-file-transfer-linux#31]
>$ cp test.txt ~/mtp/SECZ9519043CHOHB/Documents/test.txt
cp: невозможно создать обычный файл «/home/repsac/mtp/SECZ9519043CHOHB/Documents/test.txt»: Ошибка ввода/вывода
$ ls ~/mtp/SECZ9519043CHOHB/Documents/
итого 0
-rw-r--r-- 1 root root 0 янв  1  1970 test.txt

Пробовал и так и сяк, и на разные storage создается файл 0 длины и всё.

**Comment by whoozle** [comment]
Какое устройство? запустите пожалуйста ./afs-mtp-mount с ключами -d и -f

**Comment by whoozle** [comment]
Если это не андроид телефон (или меньше чем 3.x), то увы, не заработает, SendPartialObject это андроидное расширение, а по другому частичную запись не сделать никак в mtp. 
Возможно нужно предупреждать об этом в консоли, либо возвращать ошибку read only filesystem. 

покажите вывод ./aft-mtp-cli пожалуйста.

**Comment by repsac-by** [comment]
Samsung S4 i9500  Android  5.0.1
>FUSE library version: 2.9.3
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.23
flags=0x0003f7fb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40

**Comment by whoozle** [comment]
Нужны логи до ошибки. :)

**Comment by repsac-by** [comment]
Чтение прекрасно работает, фильм с телефона можно смотреть и мотать мгновенно с libmtp так не получается, оно вначале выкачивает весь файл.

>microsoft.com: 1.0; microsoft.com/WMPPD: 11.0; microsoft.com/WMPPD: 10.0; microsoft.com/WMDRMPD:10.1; microsoft.com/playready:1.10;samsung.com/kies:2.1;samsung.com/sidesync3.1;
Samsung Electronics Co., Ltd. GT-I9500 I9500XXUHOB8 RF1D56N5ETJ
supported op codes: 1001 1002 1003 1004 1005 1006 1007 1008 1009 100b 100c 100d 1014 1015 1016 101b 9810 9811 9802 9801 9803 9804 9805 9806 9201 9202 100a 1011 1012 1017 9807 9808 9100 9101 9102 9103 9104 9105 9106 9107 9108 9109 910a 910b 910c 910d 910e 910f 9110 9111 9112 9113 9114 9115 9116 9501 9502 9503 9504 
supported properties: 5001 d401 d402 d404 d407 d101 d102 d103 d104 d105

**Comment by repsac-by** [comment]
Как получить логи ошибки?
Я еще не разобрался как подключить отладку к fuse.

**Comment by whoozle** [comment]
Запускаете как обычно, ./aft-mtp-mount -d -f <mountpoint> и оно прямо в эту же консоль пишет все операции над файлами.

Хотя я вижу что самсунг не поддерживает расширения андроида для частичной записи, (95c1-95c5) Я посмотрю на остальные команды, у вас список гораздо длиннее чем у меня на nexus 5 :), может быть там что-то похожее есть.

**Comment by repsac-by** [comment]
Вот же, я слоупок )))
>FUSE library version: 2.9.3
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.23
flags=0x0003f7fb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 9441
getattr /
   unique: 2, success, outsize: 120
unique: 3, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 9443
   unique: 3, success, outsize: 32
unique: 4, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9443
readdir[0] from 0
   unique: 4, success, outsize: 168
unique: 5, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9443
   unique: 5, success, outsize: 16
unique: 6, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 6, success, outsize: 16
unique: 7, opcode: LOOKUP (1), nodeid: 1, insize: 57, pid: 9443
LOOKUP /SECZ9519043CHOHB
getattr /SECZ9519043CHOHB
   NODEID: 2
   unique: 7, success, outsize: 144
unique: 8, opcode: LOOKUP (1), nodeid: 1, insize: 59, pid: 9443
LOOKUP /SECZ9519043CHOHB01
getattr /SECZ9519043CHOHB01
   NODEID: 3
   unique: 8, success, outsize: 144
unique: 9, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 9445
getattr /
   unique: 9, success, outsize: 120
unique: 10, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 9445
   unique: 10, success, outsize: 32
unique: 11, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9445
readdir[0] from 0
   unique: 11, success, outsize: 168
unique: 12, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9445
   unique: 12, success, outsize: 16
unique: 13, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 13, success, outsize: 16
unique: 14, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 9426
getattr /
   unique: 14, success, outsize: 120
unique: 15, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 9446
getattr /
   unique: 15, success, outsize: 120
unique: 16, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 9446
   unique: 16, success, outsize: 32
unique: 17, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9446
readdir[0] from 0
   unique: 17, success, outsize: 168
unique: 18, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9446
   unique: 18, success, outsize: 16
unique: 19, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 19, success, outsize: 16
unique: 20, opcode: LOOKUP (1), nodeid: 1, insize: 57, pid: 9446
LOOKUP /SECZ9519043CHOHB
getattr /SECZ9519043CHOHB
   NODEID: 2
   unique: 20, success, outsize: 144
unique: 21, opcode: LOOKUP (1), nodeid: 1, insize: 59, pid: 9446
LOOKUP /SECZ9519043CHOHB01
getattr /SECZ9519043CHOHB01
   NODEID: 3
   unique: 21, success, outsize: 144
unique: 22, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 9447
getattr /
   unique: 22, success, outsize: 120
unique: 23, opcode: OPENDIR (27), nodeid: 1, insize: 48, pid: 9447
   unique: 23, success, outsize: 32
unique: 24, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9447
readdir[0] from 0
   unique: 24, success, outsize: 168
unique: 25, opcode: READDIR (28), nodeid: 1, insize: 80, pid: 9447
   unique: 25, success, outsize: 16
unique: 26, opcode: RELEASEDIR (29), nodeid: 1, insize: 64, pid: 0
   unique: 26, success, outsize: 16
unique: 27, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 9426
getattr /
   unique: 27, success, outsize: 120
unique: 28, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 9448
getattr /
   unique: 28, success, outsize: 120
unique: 29, opcode: LOOKUP (1), nodeid: 1, insize: 57, pid: 9448
LOOKUP /SECZ9519043CHOHB
getattr /SECZ9519043CHOHB
   NODEID: 2
   unique: 29, success, outsize: 144
unique: 30, opcode: OPENDIR (27), nodeid: 2, insize: 48, pid: 9448
   unique: 30, success, outsize: 32
unique: 31, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 9448
readdir[0] from 0
   unique: 31, success, outsize: 840
unique: 32, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 9448
   unique: 32, success, outsize: 16
unique: 33, opcode: RELEASEDIR (29), nodeid: 2, insize: 64, pid: 0
   unique: 33, success, outsize: 16
unique: 34, opcode: LOOKUP (1), nodeid: 2, insize: 49, pid: 9448
LOOKUP /SECZ9519043CHOHB/Download
getattr /SECZ9519043CHOHB/Download
   NODEID: 4
   unique: 34, success, outsize: 144
unique: 35, opcode: LOOKUP (1), nodeid: 2, insize: 50, pid: 9448
LOOKUP /SECZ9519043CHOHB/Documents
getattr /SECZ9519043CHOHB/Documents
   NODEID: 5
   unique: 35, success, outsize: 144
unique: 36, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 9449
getattr /SECZ9519043CHOHB
   unique: 36, success, outsize: 120
unique: 37, opcode: OPENDIR (27), nodeid: 2, insize: 48, pid: 9449
   unique: 37, success, outsize: 32
unique: 38, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 9449
readdir[0] from 0
   unique: 38, success, outsize: 840
unique: 39, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 9449
   unique: 39, success, outsize: 16
unique: 40, opcode: RELEASEDIR (29), nodeid: 2, insize: 64, pid: 0
   unique: 40, success, outsize: 16
unique: 41, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 9426
getattr /SECZ9519043CHOHB
   unique: 41, success, outsize: 120
unique: 42, opcode: GETATTR (3), nodeid: 1, insize: 56, pid: 9450
getattr /
   unique: 42, success, outsize: 120
unique: 43, opcode: LOOKUP (1), nodeid: 1, insize: 57, pid: 9450
LOOKUP /SECZ9519043CHOHB
getattr /SECZ9519043CHOHB
   NODEID: 2
   unique: 43, success, outsize: 144
unique: 44, opcode: OPENDIR (27), nodeid: 2, insize: 48, pid: 9450
   unique: 44, success, outsize: 32
unique: 45, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 9450
readdir[0] from 0
   unique: 45, success, outsize: 840
unique: 46, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 9450
   unique: 46, success, outsize: 16
unique: 47, opcode: RELEASEDIR (29), nodeid: 2, insize: 64, pid: 0
unique: 48, opcode: LOOKUP (1), nodeid: 2, insize: 50, pid: 9450
LOOKUP /SECZ9519043CHOHB/Documents
getattr /SECZ9519043CHOHB/Documents
   unique: 47, success, outsize: 16
   NODEID: 5
   unique: 48, success, outsize: 144
unique: 49, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 9451
getattr /SECZ9519043CHOHB
   unique: 49, success, outsize: 120
unique: 50, opcode: OPENDIR (27), nodeid: 2, insize: 48, pid: 9451
   unique: 50, success, outsize: 32
unique: 51, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 9451
readdir[0] from 0
   unique: 51, success, outsize: 840
unique: 52, opcode: READDIR (28), nodeid: 2, insize: 80, pid: 9451
   unique: 52, success, outsize: 16
unique: 53, opcode: RELEASEDIR (29), nodeid: 2, insize: 64, pid: 0
   unique: 53, success, outsize: 16
unique: 54, opcode: GETATTR (3), nodeid: 2, insize: 56, pid: 9426
getattr /SECZ9519043CHOHB
   unique: 54, success, outsize: 120
unique: 55, opcode: LOOKUP (1), nodeid: 1, insize: 57, pid: 9453
LOOKUP /SECZ9519043CHOHB
getattr /SECZ9519043CHOHB
   NODEID: 2
   unique: 55, success, outsize: 144
unique: 56, opcode: LOOKUP (1), nodeid: 2, insize: 50, pid: 9453
LOOKUP /SECZ9519043CHOHB/Documents
getattr /SECZ9519043CHOHB/Documents
   NODEID: 5
   unique: 56, success, outsize: 144
unique: 57, opcode: LOOKUP (1), nodeid: 5, insize: 49, pid: 9453
LOOKUP /SECZ9519043CHOHB/Documents/test.txt
getattr /SECZ9519043CHOHB/Documents/test.txt
g_wrapper->GetAttr(path, stbuf) failed: Get: invalid response code InvalidParentObject (0x201a)   unique: 57, error: -5 (Input/output error), outsize: 16

**Comment by whoozle** [comment]
Ой, тут не та ошибка, которую я ожидал увидеть, а у вас в /SECZ9519043CHOHB/ список storage'ей есть? по идее в руте, как в libmtp должен быть списочек.

**Comment by whoozle** [comment]
сделайте pull, пожалуйста. Вечером проверю на своем старом S3. :)

**Comment by repsac-by** [comment]
libmtp:
>drwxr-xr-x 10 repsac repsac 0 фев 19  1970 Card
drwxr-xr-x 23 repsac repsac 0 фев 19  1970 Phone

aft-fuse: 
>
drwxr-xr-x 2 root root 0 янв  1  1970 SECZ9519043CHOHB
drwxr-xr-x 2 root root 0 янв  1  1970 SECZ9519043CHOHB01

**Comment by whoozle** [comment]
а, понял) сделайте pull опять, пожалуйста.

**Comment by repsac-by** [comment]
Названия стали Card и Phone
Но файл пока так же не копируется

**Comment by repsac-by** [comment]
>FUSE library version: 2.9.3
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.23
flags=0x0003f7fb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000011
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 46, pid: 10121
LOOKUP /Phone
getattr /Phone
   NODEID: 2
   unique: 2, success, outsize: 144
unique: 3, opcode: LOOKUP (1), nodeid: 2, insize: 50, pid: 10121
LOOKUP /Phone/Documents
getattr /Phone/Documents
   NODEID: 3
   unique: 3, success, outsize: 144
unique: 4, opcode: LOOKUP (1), nodeid: 3, insize: 49, pid: 10121
LOOKUP /Phone/Documents/test.txt
getattr /Phone/Documents/test.txt
   NODEID: 4
   unique: 4, success, outsize: 144
unique: 5, opcode: OPEN (14), nodeid: 4, insize: 48, pid: 10121
open flags: 0x8001 /Phone/Documents/test.txt
   open[0] flags: 0x8001 /Phone/Documents/test.txt
   unique: 5, success, outsize: 32
unique: 6, opcode: SETATTR (4), nodeid: 4, insize: 128, pid: 10121
truncate /Phone/Documents/test.txt 0
g_wrapper->Truncate(path, offset) failed: Get: invalid response code OperationNotSupported (0x2005)   unique: 6, error: -5 (Input/output error), outsize: 16
unique: 7, opcode: RELEASE (18), nodeid: 4, insize: 64, pid: 0
   unique: 7, success, outsize: 16

**Comment by whoozle** [comment]
`microsoft.com: 1.0; microsoft.com/WMPPD: 11.0; microsoft.com/WMPPD: 10.0; microsoft.com/WMDRMPD:10.1; microsoft.com/playready:1.10;samsung.com/kies:2.1;samsung.com/sidesync3.1;
Samsung Electronics Co., Ltd. SM-G900F XXXXXXXXXXXX XXXXXXXX
supported op codes: 1001 1002 1003 1004 1005 1006 1007 1008 1009 100b 100c 100d 1014 1015 1016 101b 9810 9811 9802 9801 9803 9804 9805 9806 9201 9202 100a 1011 1012 1017 9807 9808 9100 9101 9102 9103 9104 9105 9106 9107 9108 9109 910a 910b 910c 910d 910e 910f 9110 9111 9112 9113 9114 9115 9116 9501 9502 9503 9504 
supported properties: 5001 d401 d402 d404 d407 d101 d102 d103 d104 d105 
`

**Comment by whoozle** [comment]
Печально, но самсунг выбросил андроидные расширения, которые позволяют записывать файлы. Думаю надо проверять это и выводить ошибку в fuse.

**Comment by whoozle** [comment]
libmtp читает объект и потом его целиком пишет на write. это слишком жестоко, закачивайте через ui или через cli тулзу. :)

**Comment by repsac-by** [comment]
жаль :(

**Comment by whoozle** [comment]
у меня через fuse закачивается где-то 1-2Mb/s, через ui до 15-20 :)

**Comment by whoozle** [comment]
Я пока не буду закрывать, надо внимательно изучить поддерживаемые операции, к тому же у меня есть старый S3. Может быть kios умеет что-нибудь такое.

**Comment by repsac-by** [comment]
тогда не жаль :)

**Comment by whoozle** [comment]
Не могли бы вы проверить последнюю версию, что она выдает read-only filesystem в качестве ошибки?

**Comment by repsac-by** [comment]
прямо сейчас не могу пришлось загрузиться в win по работе... примерно через час проверю

**Comment by whoozle** [comment]
Ничего страшного. :)

**Comment by repsac-by** [comment]
Предупреждение выскакивает, но реально монтиурется c опцие rw и файл 0 длинны можно создать. Если есть возможность то лучше в такой ситуации принудительно ставить ro.

**Comment by whoozle** [comment]
Забыл про create. :) Добавил туда проверку тоже, пульнитесь пожалуйста.

**Comment by repsac-by** [comment]
всё ОК. выкидывает ошибку 
>cp: невозможно создать обычный файл «/home/repsac/mtp/Phone/Documents/CMakeCache.txt»: Файловая система доступна только для чтения

**Comment by whoozle** [comment]
Я добавил в единственные флаги, где нашел - в statvfs readonly. если несложно, посмотрите.

**Comment by repsac-by** [comment]
монтирует все равно rw
хотя может это уже и не так важно

**Comment by whoozle** [comment]
до чего дотянулся, нигде ничего такого нет, к сожалению. пишите в самсунг гневные письма :(
