### ISSUE TITLE
Application does not launch

### ISSUE THREAD

**Issue by rpolley** [whoozle/android-file-transfer-linux#315]
Currently on Fedora 34, this application does not launch. If I look in journalctl I see the following message: android-file-transfer[3918]: QSocketNotifier: Can only be used with threads started with QThread.

**Comment by rpolley** [comment]
(this is using whatever version of this dnf installs)

**Comment by viveksray17** [comment]
I am using the appimage. some of it's dependecies are `gvfs-mtp` `fuse2` and `mtpfs`. Even though it is an appimage it certainly requires these packages to be installed. Otherwise it doesn't work

**Comment by whoozle** [comment]
shouldn't be mtpfs really but others look valid, thanks for the investigation, I'll take a look how to add them, PRs welcome :)

**Comment by viveksray17** [comment]
> shouldn't be mtpfs really but others look valid, thanks for the investigation, I'll take a look how to add them, PRs welcome :)

ok yeah `mtpfs` is not required. It works without it also

**Comment by viveksray17** [comment]
yes it works now 🥳

**Comment by whoozle** [comment]
hooray, thanks for checking this out!
