### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by jahway603** [whoozle/android-file-transfer-linux#318]
Please add a dark theme (or a theme that's less bright) as the current brightness is an accessibility issue.

**Comment by whoozle** [comment]
it should switch automatically, are all Qt apps are too bright for you?

**Comment by whoozle** [comment]
can you make a screenshot please?

**Comment by jahway603** [comment]
I got a dark QT theme after setting the environment variable QT_QPA_PLATFORMTHEME to qt5ct and then configuring the dark theme in that application.
