### ISSUE TITLE
rmdir deletes non-empty directories recursively

### ISSUE THREAD

**Issue by cunlem** [whoozle/android-file-transfer-linux#329]
When device is mounted as FUSE filesystem `rmdir` command deletes entire directory hierarchies while it should only remove empty ones.

Same issue as with https://github.com/hanwen/go-mtpfs/issues/103

Version: 4.2-1 (Ubuntu 22.04)

**Comment by whoozle** [comment]
It's default MTP behaviour :grimacing: 
Although we should stick to unix way, thanks!

**Comment by mnalis** [comment]
Agreed, attempting to rmdir(2) directory which is non-empty should fail with `ENOTEMPTY`
