### ISSUE TITLE
QtCreator compilation problems

### ISSUE THREAD

**Issue by trufanov-nok** [whoozle/android-file-transfer-linux#33]
Hi,
I'm trying to build the project via QtCreator and faced with few problems which I would like to discuss here. Let's move step by step.

I'm opening qt/qt.pro
and trying to build it. Getting:
```
../../android-file-transfer-linux/mtp/usb/BulkPipe.h:22:24: fatal error: usb/Device.h: No such file or directory
 #include <usb/Device.h>
```
Same for `#include <usb/Interface.h>`
There are 3 Device.h and 2 Interface.h in project. Which one shall be linked? If it depends than could you add some switch to qt.pro for these build modes?

**Comment by whoozle** [comment]
Oh, this file should be removed. Please open root CMakeLists.txt as a project.

**Comment by whoozle** [comment]
Can I close the issue?

**Comment by trufanov-nok** [comment]
It seems I can make a debug build with CMakeLists.txt and `-DCMAKE_BUILD_TYPE=Debug` flag. AT this point that's all I need. So problem may be closed.
