### ISSUE TITLE
Bug (?) in Device::FindFirst()

### ISSUE THREAD

**Issue by kirillnow** [whoozle/android-file-transfer-linux#333]
Going by the code of this function, aft-mtp-mount should support filtering devices by "vendor:product".
Example: `aft-mtp-mount -D 0e8d:2008  /tmp/mtp` 
It is a very useful feature for other script and apps.
But to do so, the following line
`if (device && device->Matches(filter))`
should be changed to
`if (device && ((vendor >= 0 && product >= 0) || device->Matches(filter)))`

**Comment by whoozle** [comment]
fixed in a9495bfd712a72011449af6a6d40bc4fc41592e4
Thank you for reporting this!
