### ISSUE TITLE
Support uid and gid designation for cli mount?

### ISSUE THREAD

**Issue by NathanIceSea** [whoozle/android-file-transfer-linux#334]
Currently with Debian 12 and Manjaro KDE tested, aft-mtp-mount called as normal user still mounts fs with root owner/group. 

The only way to have read write access for normal user is to use `allow_other` option without `default_permissions` option, which compromises security.

Is it possible to support `st_uid` and `st_gid` fuse filesystem permission by something like `uid` and `gid` options?

**Comment by whoozle** [comment]
Thanks for noticing this, previously fuse filled those fields automatically, should be fixed in 56c8d84a82ecfd557f72e36f9ced4b6b75dbe3b9, if it's not, please reopen this issue
