### ISSUE TITLE
Help printing is too late

### ISSUE THREAD

**Issue by KorespondentAda** [whoozle/android-file-transfer-linux#335]
`aft-mtp-mount --help` won't work if there is no device, if it locked, blocked by other process or, probably, any other error occured in between arguments reading and its actual processing. So I can't see help message if working conditions not met.
I think code for printing help message should be reached before any actual work and troubleshooting in case I just want to see how to call executable and what to pass as arguments. There is no manual or infopage and it's OK, but only help I have is blocked by program logic.

**Comment by whoozle** [comment]
fixed in 6e9ac2dfa32a962e89c28999633ee3c7f8b5c4af
Thanks! :+1:
