### ISSUE TITLE
libmtp clarification

### ISSUE THREAD

**Issue by dkwo** [whoozle/android-file-transfer-linux#337]
i'm using v4.2 (as packaged in void linux).
without installing the separate package libmtp, i'm unable to use aft-mtp-mount on my phone (pixel 6a).
i noticed that aft vendors its own libmtp-ng.so.4.2.0
is aft supposed to work without libmtp (which udev group? plugdev?), conflict with the libmtp package, or depend on it?

also, are distros supposed to use the continuum tag, or stick with 4.2?

thanks

**Comment by dkwo** [comment]
concretely, without libmtp:
```
$ groups dkwo 
dkwo : dkwo wheel audio plugdev users _seatd socklog
$ aft-mtp-mount ~/mnt 
connect failed: no MTP device found
```
while it mounts fine with it.

**Comment by whoozle** [comment]
No, AFTL has its own MTP implementation and does not use libmtp. My wild guess is that it contains udev rules to allow MTP devices to be readable by anyone or plugdev. 

Try passing -v to `aft-mtp-mount` and check which devices it tries to open

**Comment by dkwo** [comment]
I see. Without libmtp:
```
$ lsusb | grep Pixel 
Bus 001 Device 015: ID 18d1:4ee1 Google Inc. Nexus/Pixel Device (MTP)
$ aft-mtp-mount -v mnt 
connect failed: no MTP device found
$ ls -lt /dev/bus/usb/001                                                
total 0
crw-rw-r-- 1 root root 189, 14 Dec 12 15:06 015
...(similar entries)
```

**Comment by whoozle** [comment]
ouch, probably not the best way of fixing that - try extract udev rules into separate package (and call it plugdev for instance). 

Then the package will provide user group plugdev and register udev rules. Normally different udev/rules.d could have duplicated code (in case you have plugdev + libmtp installed together), it should just work

**Comment by dkwo** [comment]
by extract, you mean from libmtp? as I don't see any udev rules in aftl..

if so, then i'd split a subpackage libmtp-tools (containing the binaries) from libmtp (leaving here only usr/lib and udev rules) and make aftl depend on the latter?

**Comment by dkwo** [comment]
(the libmtp and libmtp-ng should not conflict anyway..)

**Comment by whoozle** [comment]
I only meant that this set of udev rules would be useful even without AFTL or libmtp. It's just sane to have an access to your pluggable usb device

**Comment by dkwo** [comment]
thanks for the clarifications. i'll try to split a subpkg of libmtp with just udev rules, and make aftl depend on this.
