### ISSUE TITLE
Mount `/` instead of `/storage/emulated/0/`

### ISSUE THREAD

**Issue by bphd** [whoozle/android-file-transfer-linux#339]

**Comment by whoozle** [comment]
Can you start GUI and check if storage drop down is working for you?

**Comment by bphd** [comment]
Well I can acheive to mount as is when connecting, it mounts `/storage/emulated/0/`

> Can you start GUI and check if storage drop down is working for you?

**Comment by whoozle** [comment]
The reason I'm asking, is that MTP can only access file system via "storages". Their list is in that drop down I mentioned, also there's a way of getting "combined" view of all storages all together. If there's no root - then it's not possible.

**Comment by bphd** [comment]
I'm rooted but I want to know how to modify the content of that drop-down list, to make appearing root

**Comment by whoozle** [comment]
it's sent via MTP protocol, I guess you need to look into android MTP host sources to achieve that, not MTP protocol itself

**Comment by bphd** [comment]
Where to look that?

**Comment by whoozle** [comment]
I think here:

https://android.googlesource.com/platform/packages/services/Mtp/+/refs/heads/main/src/com/android/mtp

I think the host side MTP entry point is 

https://android.googlesource.com/platform/packages/services/Mtp/+/refs/heads/main/src/com/android/mtp/MtpService.java

But I'm no android expert at all. 

There's also kernel helper for transferring files, but I guess it's irrelevant in a case you want to expose root fs.
