### ISSUE TITLE
Wrong encoding for file names on the device, redundant ISO-8859-1 -> UTF-8 conversion

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#34]
The program incorrectly displays non-English file names on the device and downloads them that way. Looks like they are stored as UTF-8, but AFTL converts them from ISO-8859-1 to UTF-8. For example, «Раскопанная Библия» превратилось в «_Ð Ð°Ñ?ÐºÐ¾Ð¿Ð°Ð½Ð½Ð°Ñ? Ð?Ð¸Ð±Ð»Ð¸Ñ?_.»

**Comment by tkzv** [comment]
Observed on Samsung Galaxy Tab Pro SM-T525.

**Comment by whoozle** [comment]
I'm converting strings from UTF-16 to UTF-8, no iso conversion must be involved. What version of Qt do you use?

**Comment by tkzv** [comment]
Qt 4.8.5.

**Comment by whoozle** [comment]
fixed in 33f3a0916a89419ee708d8c3d45510dcef603a34
see commit message for details if you're interested.
