### ISSUE TITLE
Add more shortcuts for directory navigation

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#36]
Currently only "Esc" is supported for going up one level. It would be batter to add more familiar "BkSp" and "Alt-up arrow".

Also it would be more convenient to allow to use numpad "Enter" to go into a directory (in addition to main block "Enter").

**Comment by tkzv** [comment]
And could you add shortcuts for deleting (e.g. "Del" and "Del") and renaming files?

**Comment by whoozle** [comment]
added after 731b1ff1097141d0e24ddcc2d81570130deba5bd
i've added keypad enter as well, but it does not work for me (but could be caught in designer while editing the shortcut). So, if you're definitely want keypad 'Enter' as shortcut please file another issue. :)

**Comment by whoozle** [comment]
also added delete confirmation dialog
