### ISSUE TITLE
Uploading to tab's card doesn't work.

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#37]
I am using Samsung Galaxy Tab Pro SM-T525. Uploading files to the tab's internal storage works fine. Uploading the same files to the tab's removable flash card doesn't work. I keep getting errors like 

> uploading file  "/home/user/books/Spoor/Spoor2.htm"  failed:  Get: invalid response code GeneralError (0x2002)

**Comment by whoozle** [comment]
is it fuse related issue?

**Comment by tkzv** [comment]
No, this happens from GUI. FUSE doesn't allow to apload anything anywhere.

**Comment by tkzv** [comment]
Forgot to mention: when I upload a file to a removable card, an identical file is created in .mtp/ directory on the tab's internal disk; when I upload next file with the same extension, it overwrites the previous one.

**Comment by whoozle** [comment]
might be fixed after #27

**Comment by whoozle** [comment]
could you test new version please? I added storage selection (do not set it to "All storages" though)

**Comment by whoozle** [comment]
this might happen if file already exists

**Comment by whoozle** [comment]
can you please check the latest master branch?

**Comment by tkzv** [comment]
Thanks, it works! At least for the videos I tried so far.

Progress bar may reach 100% long before the upload finishes.

**Comment by tkzv** [comment]
Works for books and archives. Closing.
