### ISSUE TITLE
Progress bar displays wrong values

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#38]
When I upload to a tab large volume at once (over 1.2G), the progress bar seems to reach 100% at about 1100-1200 M regardless of actual volume, be it 1.5G or 5G.

**Comment by whoozle** [comment]
I found qt4-related issue, fixed in 30d59a8b5fc8ea95ab0680f73310722871265007
please test

**Comment by tkzv** [comment]
Works correctly now.
