### ISSUE TITLE
Changes on the tab are not reflected until the cable is replugged

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#39]
If you create/delete/move/rename file or directory on the device using the device controls, the program won't notiice the changes until you unplug the device and plug it in again. Quitting and restarting the program doesn't seem to help.

**Comment by whoozle** [comment]
Android spawns mtp-daemon every time you plug the cable. Maybe this is related to #27 . Could you create directory via fuse? 
./aft-fuse-mount <mountpoint>
It might say that your filesystem is readonly ( #31 ), but it will not prevent you from creating directories. 
Seems to be android's MTP implementation does not process 'any' storage destination well. FUSE wrapper sets storage explicitly.

**Comment by tkzv** [comment]
Do you mean ./aft-mtp-mount ?

GUI program refuses to start if the device is already connected via FUSE. Should I file a bug?

FUSE mounting has the same issue. I can create directories on the tab via FUSE, but if I change something, I cannot see it by FUSE until I unplug the cable and plug it back in.

**Comment by tkzv** [comment]
Just in case: the device is Samsung Galaxy Tab Pro SM-T525, and it lacks Android MTP extensions.

**Comment by whoozle** [comment]
>GUI program refuses to start if the device is already connected via FUSE. Should I file a bug?
No, this is intended. You cannot share usb device.

**Comment by whoozle** [comment]
Could you please uncomment the following line (Session.cpp:136) and test once again? MTP specification is unclear about whether I need sending empty object after creating association(directory) or not. Google devices returns error 'no valid object info', so I considered that it's not needed. 

```
//SendObject(std::make_shared<ByteArrayObjectInputStream>(ByteArray()));
```

**Comment by whoozle** [comment]
could you test it now? I added storage selection combo box and many other improvements.

**Comment by tkzv** [comment]
Works. A "Refresh" button would be convenient to have.
