### ISSUE TITLE
Deleting files may cause segmentation fault

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#40]
I cannot reproduce this bug reliably, but occasionally deleting all files in a directory results in segmentation fault. The console output looks like this (there were 3 files):
>remove rows  1   1 
>remove rows  0   1 
>remove rows  2   1 
>Segmentation fault

The last file is not deleted. Deleting it fron the second try works.

**Comment by tkzv** [comment]
Markup error: the last line isn't a part of console output.

**Comment by whoozle** [comment]
should be fixed in 1335b80c1a8595746a3619850228c572cc81eb6e

**Comment by tkzv** [comment]
Couldn't reproduce in the new version.
