### ISSUE TITLE
Incomprehencible error from using GUI after FUSE

### ISSUE THREAD

**Issue by tkzv** [whoozle/android-file-transfer-linux#44]
Observed for ru_RU.UTF8 locale. When I mount the device with aft-mtp-mount and then try to launch android-file-transfer, a messagebox appears with something like:

> ioctl(_fd, USBDEVFS_CLAIMINTERFACE, &interfaceNumber): Đ£ÑœÑŸÑ€Đ¾Đ¹ÑœÑŸĐ¹Đ¾ ...

The message seems to have been converted from ISO-8859-1 to UTF-8, like in issue #34. This bug is observed in a version where #34 has already been fixed.

**Comment by whoozle** [comment]
fixed in 09db8ae10e18a9c7a947bc562325bd93f4120479
