### ISSUE TITLE
ioctl(_fd, USBDEVFS_CLAIMINTERFACE, &interfaceNumber): Device or resource busy

### ISSUE THREAD

**Issue by Pontorez** [whoozle/android-file-transfer-linux#53]
android-file-transfer displays the below message on start:

ioctl(_fd, USBDEVFS_CLAIMINTERFACE, &interfaceNumber): Device or resource busy

And then the program exits.

P.S. sudo ./android-file-transfer displays the same error message

P.P.S. At the same time, `adb push` works fine even under non-root user:
xx@xxx ~/Downloads/android-file-transfer-linux-2.2/build/qt $ adb push ./android-file-transfer /storage/sdcard1
4532 KB/s (531148 bytes in 0.114s)
xxx@xxx ~/Downloads/android-file-transfer-linux-2.2/build/qt $

P.P.P.S. OS=Linux Mint 17.1 64-bit

**Comment by whoozle** [comment]
usually it indicates that another process is using this interface now.

**Comment by Pontorez** [comment]
Disabled auto mount in pcmanfm preferences, now android-file-transfer works fine. Thanks
