### ISSUE TITLE
Always getting ioctl(_fd, USBDEVFS_CLAIMINTERFACE, &interfaceNumber): Device or resource busy

### ISSUE THREAD

**Issue by MagicFab** [whoozle/android-file-transfer-linux#55]
Tested with SIII and N7 tablet. Glad to provide more information.

**Comment by MiscDev** [comment]
I had the same issue. My device was been mounted by another process (Nautilus the file manager in GNOME). When I unmounted/ejected the device I could connect to it using android-file-transfer.

**Comment by MagicFab** [comment]
The n7 keeps auto-mounting, will try the SIII.

**Comment by whoozle** [comment]
This is definitely indicates that some other process is using this interface. #53 
I think I need to add messagebox with explanations instead of cryptic error. :)

**Comment by whoozle** [comment]
added message box with human readable message in commit 450418888049d9f93176b30bdcb2a039f3253425

**Comment by MagicFab** [comment]
A message is very cool but doesn't solve the issue.

**Comment by whoozle** [comment]
Well, let me help you find who's using your device. 

Open you console emulator (gnome-terminal, konsole, any of them) and type:
```lsusb``` (sudo apt-get install usbutils if it did not start)
and find your device in its output
```Bus 006 Device 070: ID 18d1:4ee2 Google Inc. Nexus 4 (debug)```
then, start fuser 
```sudo fuser /dev/bus/usb/<BUS>/<DEVICE>``` (sudo apt-get install psmisc if it did not start)
it should output something like this:
```/dev/bus/usb/006/070: 24377```
(actually, there could be more of them after semicolon, like : 24377, 24378, …)
so, 24377 is the pid of the process, so finally run:
```ps -x -q 24377```
```24377 ?        Sl    21:14 adb -P 5037 fork-server server```

**Comment by whoozle** [comment]
Added FAQ section of the README

**Comment by whoozle** [comment]
Did you find anything?
