### ISSUE TITLE
Add ability to build without Qt interface (library only)

### ISSUE THREAD

**Issue by Civil** [whoozle/android-file-transfer-linux#6]
It can be useful to have a library, so it'll be a lot easier to write custom interfaces (CLI one, gtk one, etc).

**Comment by whoozle** [comment]
There's static library (called mtp-ng) with no dependencies besides libusb-1.0.
Just added option whether to build qt application or not
https://github.com/whoozle/android-file-transfer-linux/commit/a82a353db8f0d12f6e4841247ea195e069aa42bf

it could be set via cmake -DBUILD_QT_UI=OFF or directly in CMakeCache.txt

**Comment by Civil** [comment]
And what about dynamic library?

**Comment by whoozle** [comment]
added BUILD_SHARED_LIB option :)

**Comment by Civil** [comment]
Thanks!
