### ISSUE TITLE
Error when uploading files of size 24052 (edit: any file size aligned by (n * 512 - 12) boundary)

### ISSUE THREAD

**Issue by colona** [whoozle/android-file-transfer-linux#61]
Hi, very basically:

    dd if=/dev/urandom of=/tmp/foobar bs=1 count=24052

and then, trying to upload that file:

    uploadFiles  ("/tmp/foobar")
    uploading 24052 bytes
    uploading file  "/tmp/foobar"
    uploadFile  "foobar"  as  "foobar"
    sending  24052  bytes
    new object id:  3758 , sending...
    10008 ms since the last poll call
    uploading file  "/tmp/foobar"  failed:  "timeout reaping usb urb"
    finishing queue
    drop message 0003 2001, transaction 00000023, expected: 00000024
    10010 ms since the last poll call
    finalizing commands failed:  "timeout reaping usb urb"
    finished

This happens on the HEAD and it also fails with pure ASCII files or whatever. Adding or removing a single byte from that file make the transfer work, really only the size seems to matter here, very weird…

Thanks, great work otherwise! Let me know if you need any other info.

**Comment by whoozle** [comment]
well, adding 12 bytes to the file size and got perfectly 512-bytes aligned size. :)

**Comment by whoozle** [comment]
could you pull & test please? I added ZLP flag on every short transfer.

**Comment by colona** [comment]
Yeah, works great without any problem now. Thanks a lot!
