### ISSUE TITLE
Thx for android-file-transfer

### ISSUE THREAD

**Issue by ruuns** [whoozle/android-file-transfer-linux#63]
Couldn't find any contact data to Vladimir :) Sorry for abusing the open issue system but i just want to say:

Thanks for developing this nice working piece of software. 
Got always annoying problems with mtp/mtpfs and this tools just works !!!

Keep up development, brother! You saved my nerves :+1:  :D

**Comment by whoozle** [comment]
Thanks!
I will add my email to README right away.
