### ISSUE TITLE
batch delete crash

### ISSUE THREAD

**Issue by zabbal** [whoozle/android-file-transfer-linux#64]
Attempt to select multiple files and than delete them leads to crash:
...
QXcbWindow: Unhandled client message: "XMONAD_TIMER"
QXcbWindow: Unhandled client message: "XMONAD_TIMER"
QXcbWindow: Unhandled client message: "XMONAD_TIMER"
QXcbWindow: Unhandled client message: "XMONAD_TIMER"
finished
remove rows  188   1
remove rows  189   1
remove rows  190   1
remove rows  191   1
remove rows  192   1
remove rows  193   1
fish: Job 1, 'android-file-transfer' terminated by signal SIGSEGV (Address boundary error)

**Comment by whoozle** [comment]
What version of AFT do you use? This log line seems to be long gone

**Comment by zabbal** [comment]
2.0-0ubuntu0+ppa1 from https://launchpad.net/~lucidfox/+archive/ubuntu/android-file-transfer
Having debian/ folder directly in this repo would greatly simplify building latest version in order to aid troubleshooting and bug hunting.

**Comment by whoozle** [comment]
please ask ppa maintainer to update the AFT
