### ISSUE TITLE
annoying ui pop-up

### ISSUE THREAD

**Issue by zabbal** [whoozle/android-file-transfer-linux#65]
If I upload/download 1000 files the window with progress bar is recreated for each file anew and tries to grab focus. This is very annoying - would be much nicer if window pops up once per transfer or, even better, transfer indicator added into status bar instead of separate popup so I could continue working while transfer takes place in the background.

**Comment by whoozle** [comment]
got it, thanks for the feedback

**Comment by whoozle** [comment]
the latest version has one single dialog for the whole upload/download session with progress bars
