### ISSUE TITLE
batch upload fails as well

### ISSUE THREAD

**Issue by zabbal** [whoozle/android-file-transfer-linux#66]
when attempting upload several files at once I've got first error:

uploadFile  "dexter.mp4"  as  "dexter.mp4"
sending  541220639  bytes
reaping unknown urb, usb bus conflict: 0x7eff7ecc4360 0x7eff7ecc4470
terminate called without an active exception
fish: Job 1, 'android-file-transfer' terminated by signal SIGABRT (Abort)

And subsequent start fails right away with:
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

**Comment by zabbal** [comment]
Note: quitting and starting once again gives no cryptic error.

**Comment by whoozle** [comment]
>reaping unknown urb, usb bus conflict: 0x7eff7ecc4360 0x7eff7ecc447
this usually indicates that something else accessed the device and both programs failed, because AFT caught unknown URB.

**Comment by zabbal** [comment]
Would be nice to get some more user-friendly error message in this case. Also, regardless of access failure, program should not abnormally crash with SIGABRT - would be much better to present user dialogue explaining what happened and "try again" button to spare manual start-crash-restart cycle.

**Comment by whoozle** [comment]
no urb exception in the latest version, please ask ppa maintainer to update AFT.
