### ISSUE TITLE
aft-mtp-mount - files larger than 2 GB don't uploaded

### ISSUE THREAD

**Issue by indvd00m** [whoozle/android-file-transfer-linux#67]
Can't copy file larger than 2 GB throw FUSE interface.

**Comment by whoozle** [comment]
can you copy-paste console output of the aft-mtp-cli tool ? I need to know if your device supports 64-bit object access.

**Comment by vi** [comment]
Is it easy to test if all filesystems visible through MTP are FAT-based, thus subject to filesize limitation?

**Comment by whoozle** [comment]
Aft fuse works via partial object writes, which are limited to 32 bits. Samsung removed 64 bit extensions from Android for no reason. So, it might be device/MTP limitation.

**Comment by whoozle** [comment]
no feedback, closing it
