### ISSUE TITLE
Can't create a directory: GeneralError

### ISSUE THREAD

**Issue by Civil** [whoozle/android-file-transfer-linux#7]
Though uploading files works ok.

Device: OnePlus One, CM12 Nightly (Android 5.0)

Error: SendObjectInfo: invalid response code GeneralError (0x2002)

**Comment by whoozle** [comment]
so, uploading directories/albums does not work for you either. right?

**Comment by Civil** [comment]
Uploading files works ok, but uploading directories/albums doesn't.

**Comment by whoozle** [comment]
pull and check again please, I found violation of ptp spec (missing association type value of ObjectInfo dataset)

**Comment by Civil** [comment]
Same error.

**Comment by whoozle** [comment]
Could you look into ```adb logcat``` output right after this error popped out. Maybe you could find any MTP-related error before, like java exception or something and paste it here. This could bring some light here.

**Comment by whoozle** [comment]
also I fixed zero termination for strings, could you pull and check once again please?

**Comment by Civil** [comment]
Seems to be fixed in latest master. Though I'm not sure what fixed that.
