### ISSUE TITLE
cli: Can't change to other storage

### ISSUE THREAD

**Issue by vi** [whoozle/android-file-transfer-linux#71]
```
HUAWEI H60-L12> storage-list 
00065537 volume: , description: Internal storage
00131073 volume: , description: SD card
HUAWEI H60-L12> cd 00131073
error: could not find 00131073 in path 
```

There should be a dedicated command for switching storage or (better) there should be a way to change to location by it's number.

Getting files by the number should also be supported (use case: list files, grep for some matching file, download that file). There probably should be some syntax like `@00131073` or `///00131073` to specify those numbers.

**Comment by whoozle** [comment]
fixed in latest master
