### ISSUE TITLE
cli: Recursive download (upload)

### ISSUE THREAD

**Issue by vi** [whoozle/android-file-transfer-linux#72]
```
HUAWEI H60-L12> get viv
filename = viv
error: GetObject: invalid response code GeneralError (0x2002)
```

As a minimum, it should show a helpful error message. Better just downoad recursively.

**Comment by whoozle** [comment]
download added in c280335052812ee97c09fae63a8d8f04c7f7162c

**Comment by whoozle** [comment]
upload added in 52219204b61bad6c89e05c5d5cfa6e12ae96a8a3
