### ISSUE TITLE
cli: There should be `pwd` command

### ISSUE THREAD

**Issue by vi** [whoozle/android-file-transfer-linux#73]
to print current path.

If possible, I expect `aft-mtp-cli` to actively resolve this path from object id each time `pwd` is issued, not just track and cache `cd`s.

**Comment by whoozle** [comment]
added in d1d2422f7f51967c28ed6f73cc70d9cca3edbf97

**Comment by vi** [comment]
Works in subdirectories, prints `error: Get: invalid response code GeneralError (0x2002)` in a root directory of a storage.

**Comment by whoozle** [comment]
fixed in 290158ffe62d0124f08b4177666697f7d8b27d08
