### ISSUE TITLE
tar.gz files can't be uploaded

### ISSUE THREAD

**Issue by Civil** [whoozle/android-file-transfer-linux#8]
If I'm trying to upload some tar.gz/tar.bz2 archive it's not accepted by application:
```
uploadFiles  ("/home/civil/Music/music.tar.gz")
usbfs limit:  2048 Mib
uploading file  "/home/civil/Music/music.tar.gz"
unknown format for  "music.tar.gz"
progress size 1159775167
finished
```

And it actually looks like "successful upload", but in fact file wasn't upload and no error message was shown.

Expected behavior - upload anything, even unknown formats, because it's up to user to decide what to upload and why.

**Comment by whoozle** [comment]
removed skipping of unknown files, just tested on random tar.gz, works fine for me. please pull and check

**Comment by Civil** [comment]
I don't know if it's related, but file is 0 bytes in size after copy.

**Comment by whoozle** [comment]
did you pull the new sources? https://github.com/whoozle/android-file-transfer-linux/commit/3822c03cef75a439bdf01dc4165c5653ef50a045

**Comment by Civil** [comment]
Yup. I've also tried with https://github.com/whoozle/android-file-transfer-linux/commit/ca33c0984c59e3045e48c35e60f4d66b587ce927 - same result.

**Comment by whoozle** [comment]
weird. what's your kernel version?

**Comment by Civil** [comment]
3.19.0

If you need some more debug info - tell me what you need, I'll try to get that.

**Comment by whoozle** [comment]
removed libusb dependency, could you test on the latest master?

**Comment by Civil** [comment]
Ok. Working with current master. Thanks!
