### ISSUE TITLE
add debian/ build directory

### ISSUE THREAD

**Issue by zabbal** [whoozle/android-file-transfer-linux#84]
Having debian/ directory directly in upstream source would make it easier for people to get latest version. This will also make it easier for debian/ubuntu maintainers to accept the package into repositories.

If necessary I can make pull request.

**Comment by whoozle** [comment]
I already answered to such request by email, I'm sorry, but the answer is no, I don't want to include something I could never maintain. This could end in complete mess. Debian people includes debian/ directories to their patches and I think it would be better this way. 
You could fork AFS and maintain it by yourself, merging changes from my upstream.

**Comment by Civil** [comment]
Just to mention, if you have "debian" folder just in upstream, it'll be pain to maintain this (from Debian/Ubuntu maintainer's point of view). Most likely they'll make their own folder, if they want to. But having one in "contrib" folder can be a good idea, for example.

**Comment by whoozle** [comment]
Yes, that's why I don't add various distro-specific scripts. Let the maintainer people do their work.

**Comment by Civil** [comment]
Well, having sample 'debian' folder in contrib still can be good idea. Or have an instruction how to build rpm and deb using fpm (a tool in ruby that allows to create with mostly the same code packages for debian and rhel/fedora, also simple, but lacks of some features)
