### ISSUE TITLE
Feature suggestion: recover device mount when unplugged / plugged-in again

### ISSUE THREAD

**Issue by simonbru** [whoozle/android-file-transfer-linux#86]
I figured that I often have to unplug / plug back in my devices in my day to day use, sometimes only for seconds. Also, microUSB connections tend to be flaky with some cable/phone combinations.

To mitigate this, I just run a onliner in the terminal to unmount the device and mount it again each time I need to remount it. In my case I should probably use udev to automate this process.

However it is kind of a complicated setup if you just want to use MTP once in a while, and you have to do a little scripting if you want your device to be automatically mounted only if it was mounted before being unplugged for example.

Thus it would be nice if aftp-mtp-mount could automatically recover the mount. But I don't know if it easily feasible. If not, this feature probably isn't worth it.

**Comment by whoozle** [comment]
added in 6eb5598c6beeb4df8a1ea14311a65f12c34213e9, please note that android M (6.0+) will require you to choose MTP over USB-charge in notification area every time you plugged your device phone in.

**Comment by simonbru** [comment]
This works perfectly, thanks! (and thanks for the project itself by the way).

**Comment by whoozle** [comment]
@simonbru always a pleasure! :)
