### ISSUE TITLE
Font in fileview too big

### ISSUE THREAD

**Issue by flexo3001** [whoozle/android-file-transfer-linux#90]
Hey,
i don't know if the big font is intentional but i thing it could be a bit less giant. Maybe a setting option for this would be nice.
Best Marco

![2015-10-23-170055_1366x768_scrot](https://cloud.githubusercontent.com/assets/1415596/10696374/b1aff370-79a7-11e5-810a-2e06266c225d.png)

**Comment by whoozle** [comment]
fixed in e35dde1be692b5c22e4d652af6ae901c46da5bf1
