### ISSUE TITLE
Error "timeout reaping usb urb"

### ISSUE THREAD

**Issue by proninyaroslav** [whoozle/android-file-transfer-linux#91]
Здравствуйте. Galaxy s4. При копировании файлов именно через android file transfer 2.4 происходит ошибка:

uploading file  "/home/yaroslav/Загрузки/3C_Toolbox_Pro_v1.6.4_full_rus.apk"  failed:  "timeout reaping usb urb"
finishing queue
drop message 0003 2001, transaction 00000079, expected: 0000007a
10001 ms since the last poll call
finalizing commands failed:  "timeout reaping usb urb"
finished

**Comment by whoozle** [comment]
А скажите точный размер этого файла?

**Comment by proninyaroslav** [comment]
10,93 МБ

**Comment by whoozle** [comment]
I need exact size with 1byte precision.
2 нояб. 2015 г. 7:01 PM пользователь "Yaroslav Pronin" <
notifications@github.com> написал:

**Comment by proninyaroslav** [comment]
11457440 байт.

**Comment by whoozle** [comment]
I switched off scatter gather mode, can you pull & test it once again?

**Comment by proninyaroslav** [comment]
Yes, problem is solved. I tried on various files (including on 3C_Toolbox_Pro_v1.6.4_full_rus.apk).

**Comment by whoozle** [comment]
did you check with 5c9ae333934c1d3be718fc50d625b08b70416090 revision? I increased bulk transfer buffer to 4k, instead of 512 bytes.

**Comment by proninyaroslav** [comment]
Yes, 5c9ae33 revision.
