### ISSUE TITLE
Add PPA for stable and unstable builds

### ISSUE THREAD

**Issue by Sunderland93** [whoozle/android-file-transfer-linux#92]
Hi. I create two PPA's, for stable builds (https://launchpad.net/~samoilov-lex/+archive/ubuntu/aftl-stable) and weekly GIT unstable builds (https://launchpad.net/~samoilov-lex/+archive/ubuntu/aftl-unstable)

**Comment by whoozle** [comment]
Great, thanks! The other ppa seems dead for a while, I tried to contact the owner, but no luck.
