### ISSUE TITLE
Current master's android-file-transfer GUI broken

### ISSUE THREAD

**Issue by vi** [whoozle/android-file-transfer-linux#95]
In commit 5c9ae333934c1d3be718fc50d625b08b70416090 I see broken toolbar in GUI:

![q](https://cloud.githubusercontent.com/assets/173219/10994688/f0cbb21a-8488-11e5-882d-bf356fee3a0f.png)

There are several unlabaled buttons, with correct tooltips.

**Comment by whoozle** [comment]
upload's icon fixed in 5c9ae333934c1d3be718fc50d625b08b70416090
the other missing icons must be provided by your DE :(

**Comment by vi** [comment]
DE? I just use Awesome window manager without actual IDE.

Also previously there were text labels.

**Comment by vi** [comment]
Updated again, now all labers are back in place.
