### ISSUE TITLE
cli: Can't noninteractively list non-root directory

### ISSUE THREAD

**Issue by vi** [whoozle/android-file-transfer-linux#96]
* `cli/aft-mtp-cli  ls DCIM/Camera_2` - root directory get listed
* `cli/aft-mtp-cli  ls /DCIM/Camera_2` - root directory get listed
* `cli/aft-mtp-cli  cd DCIM/Camera_2 ls` - only `cd` command executed
* `cli/aft-mtp-cli  'cd DCIM/Camera_2 ; ls'` - `error: invalid command cd DCIM/Camera_2 ; ls`
* `cli/aft-mtp-cli  cd DCIM/Camera_2 ';' ls` - only `cd` command executed

**Comment by vi** [comment]
I try to batch test listing a directory from cli, and itsead of this script:

    for i in {1..20}; do printf 'cd DCIM/Camera_2\nls\n' | socat - exec:cli/aft-mtp-cli,pty  > ttt/$i.txt;  done

I'd prefer to use something like this:

    for i in {1..20}; do cli/aft-mtp-cli  ls DCIM/Camera_2  > ttt/$i.txt;  done

**Comment by whoozle** [comment]
Honestly I don't like the idea of further development of this «another command line batch mode». You can open aft-mtp-cli with stdin/stdout redirected, and feed it any commands you wish:
```echo -n "cd /Video\nls" | ./cli/aft-mtp-cli```
works well for me. 

I will suppress banners in a few minutes, so this little batch commands should be clean and ready for further processing by any tool.

**Comment by vi** [comment]
Using redirected input is less convenient in shell scripts, especially in presense of tricky filenames that contain spaces.

**Comment by whoozle** [comment]
no more trickier than passing such names as arguments and escaping commands separators

**Comment by whoozle** [comment]
Well, ok, I see two options here:
1) double escape everything and use
```
aft-mtp-cli cd\ Camera\\\ 2 ls
```
so this will be passed in N args like 
```
cd Camera\ 2
ls
```
2) introduce some magic delimiter, which could not be used in MTP as part of the filename (; (?) 
aft-mtp-cli cd Video\ 2 \; ls
note \;, running ; as delimiter from shell will require escaping too.

Either way, escape-screwing is more-or-less required. Also, when you reach the argument limit(it's not that big actually, 4096), ~~no one hear you scream~~ the xargs will not help, because generally -cli tool require some persistent state, consistent across multiple spawned processes, which is impossibe.

**Comment by whoozle** [comment]
I could add it in any way, but I don't think I will be able to help you struggle with further limitations of it. :)

**Comment by vi** [comment]
Trying to escape string or using magic delimiters is generally hacky way to be avoided.

True way is using arrays of strings (such as command-line arguments array).

**Comment by whoozle** [comment]
you will have to escape this arrays anyway

**Comment by vi** [comment]
Shall I just prepare a pull request making it behave the way I want?

**Comment by vi** [comment]
> it's not that big actually, 4096

You can do a lot in 4096 commands.  And in modern Linux I expect it more than 4096 (something around "depending on how much virtual memory you have").

**Comment by whoozle** [comment]
well, it does not meet your expectation then. :) 
>Shall I just prepare a pull request making it behave the way I want?
no, not yet, let's figure out what works best first.

**Comment by whoozle** [comment]
c6fdba7571a2d2011b43d7093e42e6bf665fb166 
1 command == 1 argument
```
./cli/aft-mtp-cli cd\ Video ls
```
works for me
