### ISSUE TITLE
cli: Can't redirect output to file

### ISSUE THREAD

**Issue by vi** [whoozle/android-file-transfer-linux#97]
It exits early.

Workaround: execute aft-mtp-cli using socat: `socat - exec:cli/aftp-mtp-cli,pty`.

**Comment by whoozle** [comment]
Could you please be more specific? 
What do you expect? What does 'exits early' means?

**Comment by vi** [comment]
Typically after starting aftp-mtp-cli connected to device, then prints prompt and expects commands.

When stdout is not a terminal, it just exits before connecting to device or expecting commands.

**Comment by vi** [comment]
Found the offending line: https://github.com/whoozle/android-file-transfer-linux/blob/master/cli/cli.cpp#L53

**Comment by whoozle** [comment]
c7ccad950d43d6d13d2d45b410c8927698ba1391 allows you to specify -i or --interactive to override this behaviour.

**Comment by vi** [comment]
Irony is that this `-i` would be required for non-interactive (batch) use.

**Comment by whoozle** [comment]
that's the unix way, lol :D

please pull, I split debug output from output, so, -i should be ready for batch processing. Now I'm closing this one, please feel free to report any new issues.

**Comment by whoozle** [comment]
Also, I added -b/--batch, which guarantees you no prompt and interactive processing mode

32512b15825e43bf554e41896c18318a706980dc
